Kratos: Kratos::ModelPart Class Reference
Kratos::ModelPart Class Reference
ModelPart class.
#include <model_part.h>
Classes
class GetModelPartName
Public Types
Enum's
enum OwnershipType { Kratos_All, Kratos_Local, Kratos_Ghost, Kratos_Ownership_Size }
Public Types inherited from Kratos::DataValueContainer
typedef std::pair< const VariableData *, void * > ValueType
Type of the container used for variables.
typedef std::vector< ValueType > ContainerType
Type of the container used for variables.
typedef std::vector< ValueType >::iterator IteratorType
Type of the container used for variables.
typedef std::vector< ValueType >::const_iterator ConstantIteratorType
Type of the container used for variables.
typedef std::vector< ValueType >::size_type SizeType
Type of the container used for variables.
Public Types inherited from Kratos::Flags
enum FlagsList {
Flag0 = BlockType(1), Flag1 = BlockType(1) << 1, Flag2 = BlockType(1) << 2, Flag3 = BlockType(1) << 3,
Flag4 = BlockType(1) << 4, Flag5 = BlockType(1) << 5, Flag6 = BlockType(1) << 6, Flag7 = BlockType(1) << 7,
Flag8 = BlockType(1) << 8, Flag9 = BlockType(1) << 9, Flag10 = BlockType(1) << 10, Flag11 = BlockType(1) << 11,
Flag12 = BlockType(1) << 12, Flag13 = BlockType(1) << 13, Flag14 = BlockType(1) << 14, Flag15 = BlockType(1) << 15,
Flag16 = BlockType(1) << 16, Flag17 = BlockType(1) << 17, Flag18 = BlockType(1) << 18, Flag19 = BlockType(1) << 19,
Flag20 = BlockType(1) << 20, Flag21 = BlockType(1) << 21, Flag22 = BlockType(1) << 22, Flag23 = BlockType(1) << 23,
Flag24 = BlockType(1) << 24, Flag25 = BlockType(1) << 25, Flag26 = BlockType(1) << 26, Flag27 = BlockType(1) << 27,
Flag28 = BlockType(1) << 28, Flag29 = BlockType(1) << 29, Flag30 = BlockType(1) << 30
}
typedef int64_t BlockType
typedef int64_t FlagType
typedef std::size_t IndexType
Public Member Functions
Flags
KRATOS_DEFINE_LOCAL_FLAG (ALL_ENTITIES)
KRATOS_DEFINE_LOCAL_FLAG (OVERWRITE_ENTITIES)
Life Cycle
ModelPart ()
Default constructor.
ModelPart (std::string const &NewName)
Constructor with name.
ModelPart (std::string const &NewName, IndexType NewBufferSize)
Constructor with name and bufferSize.
ModelPart (ModelPart const &rOther)
Copy constructor.
~ModelPart () override
Destructor.
Operators
ModelPart & operator= (ModelPart const &rOther)
Assignment operator.
Solution Steps
IndexType CreateSolutionStep ()
IndexType CloneSolutionStep ()
IndexType CloneTimeStep ()
IndexType CreateTimeStep (double NewTime)
IndexType CloneTimeStep (double NewTime)
void OverwriteSolutionStepData (IndexType SourceSolutionStepIndex, IndexType DestinationSourceSolutionStepIndex)
void ReduceTimeStep (ModelPart &rModelPart, double NewTime)
Nodes
SizeType NumberOfNodes (IndexType ThisIndex=0) const
void AddNode (NodeType::Pointer pNewNode, IndexType ThisIndex=0)
void AddNodes (std::vector< IndexType > &NodeIds, IndexType ThisIndex=0)
template<class TIteratorType >
void AddNodes (TIteratorType nodes_begin, TIteratorType nodes_end, IndexType ThisIndex=0)
NodeType::Pointer CreateNewNode (int Id, double x, double y, double z, VariablesList *pNewVariablesList, IndexType ThisIndex=0)
NodeType::Pointer CreateNewNode (IndexType Id, double x, double y, double z, IndexType ThisIndex=0)
NodeType::Pointer CreateNewNode (IndexType Id, double x, double y, double z, double *pThisData, IndexType ThisIndex=0)
NodeType::Pointer CreateNewNode (IndexType NodeId, NodeType const &rSourceNode, IndexType ThisIndex=0)
void AssignNode (NodeType::Pointer pThisNode, IndexType ThisIndex=0)
NodeType::Pointer pGetNode (IndexType NodeId, IndexType ThisIndex=0)
NodeType & GetNode (IndexType NodeId, IndexType ThisIndex=0)
void RemoveNode (IndexType NodeId, IndexType ThisIndex=0)
void RemoveNode (NodeType &ThisNode, IndexType ThisIndex=0)
void RemoveNode (NodeType::Pointer pThisNode, IndexType ThisIndex=0)
void RemoveNodeFromAllLevels (IndexType NodeId, IndexType ThisIndex=0)
void RemoveNodeFromAllLevels (NodeType &ThisNode, IndexType ThisIndex=0)
void RemoveNodeFromAllLevels (NodeType::Pointer pThisNode, IndexType ThisIndex=0)
void RemoveNodes (Flags identifier_flag=TO_ERASE)
void RemoveNodesFromAllLevels (Flags identifier_flag=TO_ERASE)
ModelPart & GetRootModelPart ()
NodeIterator NodesBegin (IndexType ThisIndex=0)
NodeConstantIterator NodesBegin (IndexType ThisIndex=0) const
NodeIterator NodesEnd (IndexType ThisIndex=0)
NodeConstantIterator NodesEnd (IndexType ThisIndex=0) const
NodesContainerType & Nodes (IndexType ThisIndex=0)
NodesContainerType::Pointer pNodes (IndexType ThisIndex=0)
void SetNodes (NodesContainerType::Pointer pOtherNodes, IndexType ThisIndex=0)
NodesContainerType::ContainerType & NodesArray (IndexType ThisIndex=0)
template<class TDataType >
void AddNodalSolutionStepVariable (Variable< TDataType > const &ThisVariable)
VariablesList & GetNodalSolutionStepVariablesList ()
void SetNodalSolutionStepVariablesList ()
SizeType GetNodalSolutionStepDataSize ()
SizeType GetNodalSolutionStepTotalDataSize ()
Tables
SizeType NumberOfTables () const
void AddTable (IndexType TableId, TableType::Pointer pNewTable)
TableType::Pointer pGetTable (IndexType TableId)
TableType & GetTable (IndexType TableId)
void RemoveTable (IndexType TableId)
void RemoveTableFromAllLevels (IndexType TableId)
TableIterator TablesBegin ()
TableConstantIterator TablesBegin () const
TableIterator TablesEnd ()
TableConstantIterator TablesEnd () const
TablesContainerType & Tables ()
TablesContainerType::ContainerType & TablesArray ()
Properties
SizeType NumberOfProperties (IndexType ThisIndex=0) const
void AddProperties (PropertiesType::Pointer pNewProperties, IndexType ThisIndex=0)
PropertiesType::Pointer pGetProperties (IndexType PropertiesId, IndexType ThisIndex=0)
PropertiesType & GetProperties (IndexType PropertiesId, IndexType ThisIndex=0)
void RemoveProperties (IndexType PropertiesId, IndexType ThisIndex=0)
void RemoveProperties (PropertiesType &ThisProperties, IndexType ThisIndex=0)
void RemoveProperties (PropertiesType::Pointer pThisProperties, IndexType ThisIndex=0)
void RemovePropertiesFromAllLevels (IndexType PropertiesId, IndexType ThisIndex=0)
void RemovePropertiesFromAllLevels (PropertiesType &ThisProperties, IndexType ThisIndex=0)
void RemovePropertiesFromAllLevels (PropertiesType::Pointer pThisProperties, IndexType ThisIndex=0)
PropertiesIterator PropertiesBegin (IndexType ThisIndex=0)
PropertiesConstantIterator PropertiesBegin (IndexType ThisIndex=0) const
PropertiesIterator PropertiesEnd (IndexType ThisIndex=0)
PropertiesConstantIterator PropertiesEnd (IndexType ThisIndex=0) const
PropertiesContainerType & rProperties (IndexType ThisIndex=0)
PropertiesContainerType::Pointer pProperties (IndexType ThisIndex=0)
void SetProperties (PropertiesContainerType::Pointer pOtherProperties, IndexType ThisIndex=0)
PropertiesContainerType::ContainerType & PropertiesArray (IndexType ThisIndex=0)
Elements
SizeType NumberOfElements (IndexType ThisIndex=0) const
void AddElement (ElementType::Pointer pNewElement, IndexType ThisIndex=0)
void AddElements (std::vector< IndexType > &ElementIds, IndexType ThisIndex=0)
template<class TIteratorType >
void AddElements (TIteratorType elements_begin, TIteratorType elements_end, IndexType ThisIndex=0)
ElementType::Pointer CreateNewElement (std::string ElementName, IndexType Id, std::vector< IndexType > ElementNodeIds, PropertiesType::Pointer pProperties, IndexType ThisIndex=0)
ElementType::Pointer CreateNewElement (std::string ElementName, IndexType Id, Geometry< Node< 3 > >::PointsArrayType pElementNodes, PropertiesType::Pointer pProperties, IndexType ThisIndex=0)
ElementType::Pointer pGetElement (IndexType ElementId, IndexType ThisIndex=0)
ElementType & GetElement (IndexType ElementId, IndexType ThisIndex=0)
void RemoveElement (IndexType ElementId, IndexType ThisIndex=0)
void RemoveElement (ElementType &ThisElement, IndexType ThisIndex=0)
void RemoveElement (ElementType::Pointer pThisElement, IndexType ThisIndex=0)
void RemoveElementFromAllLevels (IndexType ElementId, IndexType ThisIndex=0)
void RemoveElementFromAllLevels (ElementType &ThisElement, IndexType ThisIndex=0)
void RemoveElementFromAllLevels (ElementType::Pointer pThisElement, IndexType ThisIndex=0)
void RemoveElements (Flags identifier_flag=TO_ERASE)
void RemoveElementsFromAllLevels (Flags identifier_flag=TO_ERASE)
ElementIterator ElementsBegin (IndexType ThisIndex=0)
ElementConstantIterator ElementsBegin (IndexType ThisIndex=0) const
ElementIterator ElementsEnd (IndexType ThisIndex=0)
ElementConstantIterator ElementsEnd (IndexType ThisIndex=0) const
ElementsContainerType & Elements (IndexType ThisIndex=0)
ElementsContainerType::Pointer pElements (IndexType ThisIndex=0)
void SetElements (ElementsContainerType::Pointer pOtherElements, IndexType ThisIndex=0)
ElementsContainerType::ContainerType & ElementsArray (IndexType ThisIndex=0)
Conditions
SizeType NumberOfConditions (IndexType ThisIndex=0) const
void AddCondition (ConditionType::Pointer pNewCondition, IndexType ThisIndex=0)
void AddConditions (std::vector< IndexType > &ConditionIds, IndexType ThisIndex=0)
template<class TIteratorType >
void AddConditions (TIteratorType conditions_begin, TIteratorType conditions_end, IndexType ThisIndex=0)
ConditionType::Pointer CreateNewCondition (std::string ConditionName, IndexType Id, std::vector< IndexType > ConditionNodeIds, PropertiesType::Pointer pProperties, IndexType ThisIndex=0)
ConditionType::Pointer CreateNewCondition (std::string ConditionName, IndexType Id, Geometry< Node< 3 > >::PointsArrayType pConditionNodes, PropertiesType::Pointer pProperties, IndexType ThisIndex=0)
ConditionType::Pointer pGetCondition (IndexType ConditionId, IndexType ThisIndex=0)
ConditionType & GetCondition (IndexType ConditionId, IndexType ThisIndex=0)
void RemoveCondition (IndexType ConditionId, IndexType ThisIndex=0)
void RemoveCondition (ConditionType &ThisCondition, IndexType ThisIndex=0)
void RemoveCondition (ConditionType::Pointer pThisCondition, IndexType ThisIndex=0)
void RemoveConditionFromAllLevels (IndexType ConditionId, IndexType ThisIndex=0)
void RemoveConditionFromAllLevels (ConditionType &ThisCondition, IndexType ThisIndex=0)
void RemoveConditionFromAllLevels (ConditionType::Pointer pThisCondition, IndexType ThisIndex=0)
void RemoveConditions (Flags identifier_flag=TO_ERASE)
void RemoveConditionsFromAllLevels (Flags identifier_flag=TO_ERASE)
ConditionIterator ConditionsBegin (IndexType ThisIndex=0)
ConditionConstantIterator ConditionsBegin (IndexType ThisIndex=0) const
ConditionIterator ConditionsEnd (IndexType ThisIndex=0)
ConditionConstantIterator ConditionsEnd (IndexType ThisIndex=0) const
ConditionsContainerType & Conditions (IndexType ThisIndex=0)
ConditionsContainerType::Pointer pConditions (IndexType ThisIndex=0)
void SetConditions (ConditionsContainerType::Pointer pOtherConditions, IndexType ThisIndex=0)
ConditionsContainerType::ContainerType & ConditionsArray (IndexType ThisIndex=0)
Sub model parts
SizeType NumberOfSubModelParts () const
ModelPart & CreateSubModelPart (std::string const &NewSubModelPartName)
void AddSubModelPart (ModelPart &rThisSubModelPart)
ModelPart & GetSubModelPart (std::string const &SubModelPartName)
void RemoveSubModelPart (std::string const &ThisSubModelPartName)
void RemoveSubModelPart (ModelPart &ThisSubModelPart)
SubModelPartIterator SubModelPartsBegin ()
SubModelPartConstantIterator SubModelPartsBegin () const
SubModelPartIterator SubModelPartsEnd ()
SubModelPartConstantIterator SubModelPartsEnd () const
SubModelPartsContainerType & SubModelParts ()
ModelPart * GetParentModelPart () const
bool HasSubModelPart (std::string const &ThisSubModelPartName)
Access
ProcessInfo & GetProcessInfo ()
ProcessInfo const & GetProcessInfo () const
ProcessInfo::Pointer pGetProcessInfo ()
const ProcessInfo::Pointer pGetProcessInfo () const
void SetProcessInfo (ProcessInfo::Pointer pNewProcessInfo)
void SetProcessInfo (ProcessInfo &NewProcessInfo)
SizeType NumberOfMeshes ()
MeshType::Pointer pGetMesh (IndexType ThisIndex=0)
const MeshType::Pointer pGetMesh (IndexType ThisIndex=0) const
MeshType & GetMesh (IndexType ThisIndex=0)
MeshType const & GetMesh (IndexType ThisIndex=0) const
MeshesContainerType & GetMeshes ()
MeshesContainerType const & GetMeshes () const
std::string & Name ()
std::string const & Name () const
Communicator & GetCommunicator ()
Communicator const & GetCommunicator () const
Communicator::Pointer pGetCommunicator ()
void SetCommunicator (Communicator::Pointer pNewCommunicator)
Operations
std::vector< std::string > GetSubModelPartNames ()
void SetBufferSize (IndexType NewBufferSize)
IndexType GetBufferSize ()
virtual int Check (ProcessInfo &rCurrentProcessInfo) const
run input validation
Inquiry
bool IsSubModelPart () const
Input and output
std::string Info () const override
Turn back information as a string.
void PrintInfo (std::ostream &rOStream) const override
Print information about this object.
void PrintData (std::ostream &rOStream) const override
Print object's data.
virtual void PrintInfo (std::ostream &rOStream, std::string const &PrefixString) const
Print information about this object.
virtual void PrintData (std::ostream &rOStream, std::string const &PrefixString) const
Print object's data.
Public Member Functions inherited from Kratos::DataValueContainer
DataValueContainer ()
Default constructor.
DataValueContainer (DataValueContainer const &rOther)
Copy constructor.
virtual ~DataValueContainer ()
Destructor.
template<class TDataType >
const TDataType & operator() (const VariableData &rThisVariable) const
template<class TDataType >
TDataType & operator() (const Variable< TDataType > &rThisVariable)
template<class TDataType >
const TDataType & operator() (const Variable< TDataType > &rThisVariable) const
template<class TAdaptorType >
TAdaptorType::Type & operator() (const VariableComponent< TAdaptorType > &rThisVariable)
template<class TAdaptorType >
const TAdaptorType::Type & operator() (const VariableComponent< TAdaptorType > &rThisVariable) const
template<class TDataType >
TDataType & operator[] (const VariableData &rThisVariable)
template<class TDataType >
const TDataType & operator[] (const VariableData &rThisVariable) const
template<class TDataType >
TDataType & operator[] (const Variable< TDataType > &rThisVariable)
template<class TDataType >
const TDataType & operator[] (const Variable< TDataType > &rThisVariable) const
template<class TAdaptorType >
TAdaptorType::Type & operator[] (const VariableComponent< TAdaptorType > &rThisVariable)
template<class TAdaptorType >
const TAdaptorType::Type & operator[] (const VariableComponent< TAdaptorType > &rThisVariable) const
DataValueContainer & operator= (const DataValueContainer &rOther)
Assignment operator.
template<class TDataType >
TDataType & GetValue (const Variable< TDataType > &rThisVariable)
template<class TDataType >
const TDataType & GetValue (const Variable< TDataType > &rThisVariable) const
template<class TAdaptorType >
TAdaptorType::Type & GetValue (const VariableComponent< TAdaptorType > &rThisVariable)
template<class TAdaptorType >
const TAdaptorType::Type & GetValue (const VariableComponent< TAdaptorType > &rThisVariable) const
SizeType Size ()
template<class TDataType >
void SetValue (const Variable< TDataType > &rThisVariable, TDataType const &rValue)
template<class TAdaptorType >
void SetValue (const VariableComponent< TAdaptorType > &rThisVariable, typename TAdaptorType::Type const &rValue)
template<class TDataType >
void Erase (const Variable< TDataType > &rThisVariable)
void Clear ()
template<class TDataType >
bool Has (const Variable< TDataType > &rThisVariable) const
template<class TAdaptorType >
bool Has (const VariableComponent< TAdaptorType > &rThisVariable) const
bool IsEmpty ()
KRATOS_CLASS_POINTER_DEFINITION (DataValueContainer)
Pointer definition of DataValueContainer.
Public Member Functions inherited from Kratos::Flags
Flags & operator= (Flags const &rOther)
Assignment operator.
operator bool () const
Flags operator~ () const
bool operator! () const
void AssignFlags (Flags const &rOther)
void Set (Flags ThisFlag)
void Set (Flags ThisFlag, bool Value)
void Reset (Flags ThisFlag)
void Flip (Flags ThisFlag)
void SetPosition (IndexType Position, bool Value=true)
bool GetPosition (IndexType Position) const
void FlipPosition (IndexType Position)
void ClearPosition (IndexType Position)
void Clear ()
bool Is (Flags const &rOther) const
bool IsDefined (Flags const &rOther) const
bool IsNot (Flags const &rOther) const
bool IsNotDefined (Flags const &rOther) const
KRATOS_CLASS_POINTER_DEFINITION (Flags)
Pointer definition of Flags.
Flags ()
Default constructor.
Flags (Flags const &rOther)
Copy constructor.
virtual ~Flags ()
Destructor.
const Flags & operator|= (const Flags &Other)
const Flags & operator&= (const Flags &Other)
Private Member Functions
Private Operations
void SetParentModelPart (ModelPart *pParentModelPart)
template<typename TEntitiesContainerType >
void AddEntities (TEntitiesContainerType const &Source, TEntitiesContainerType &rDestination, Flags Options)
Private Attributes
Member Variables
std::string mName
IndexType mBufferSize
ProcessInfo::Pointer mpProcessInfo
TablesContainerType mTables
std::vector< IndexType > mIndices
MeshesContainerType mMeshes
VariablesList * mpVariablesList
Communicator::Pointer mpCommunicator
ModelPart * mpParentModelPart
SubModelPartsContainerType mSubModelParts
Type Definitions
typedef std::size_t IndexType
typedef std::size_t SizeType
typedef Dof< double > DofType
typedef PointerVectorSet< DofType, SetIdentityFunction< DofType >, std::less< SetIdentityFunction< DofType >::result_type >, std::equal_to< SetIdentityFunction< DofType >::result_type >, DofType * > DofsArrayType
typedef Node< 3 > NodeType
typedef Properties PropertiesType
typedef Element ElementType
typedef Condition ConditionType
typedef Mesh< NodeType, PropertiesType, ElementType, ConditionType > MeshType
typedef PointerVector< MeshType > MeshesContainerType
typedef MeshType::NodesContainerType NodesContainerType
Nodes container. Which is a vector set of nodes with their Id's as key.
typedef MeshType::NodeIterator NodeIterator
typedef MeshType::NodeConstantIterator NodeConstantIterator
typedef MeshType::PropertiesContainerType PropertiesContainerType
Properties container. Which is a vector set of Properties with their Id's as key.
typedef MeshType::PropertiesIterator PropertiesIterator
typedef MeshType::PropertiesConstantIterator PropertiesConstantIterator
typedef MeshType::ElementsContainerType ElementsContainerType
Element container. A vector set of Elements with their Id's as key.
typedef MeshType::ElementIterator ElementIterator
typedef MeshType::ElementConstantIterator ElementConstantIterator
typedef MeshType::ConditionsContainerType ConditionsContainerType
Condintions container. A vector set of Conditions with their Id's as key.
typedef MeshType::ConditionIterator ConditionIterator
typedef MeshType::ConditionConstantIterator ConditionConstantIterator
typedef Table< double, double > TableType
Defining a table with double argument and result type as table type.
typedef PointerVectorMap< SizeType, TableType > TablesContainerType
The container of the tables. A vector map of the tables.
typedef TablesContainerType::iterator TableIterator
typedef TablesContainerType::const_iterator TableConstantIterator
typedef PointerHashMapSet< ModelPart, boost::hash< std::string >, GetModelPartName, ModelPart * > SubModelPartsContainerType
The container of the sub model parts. A hash table is used.
typedef SubModelPartsContainerType::iterator SubModelPartIterator
Iterator over the sub model parts of this model part.
typedef SubModelPartsContainerType::const_iterator SubModelPartConstantIterator
Constant iterator over the sub model parts of this model part.
KRATOS_CLASS_POINTER_DEFINITION (ModelPart)
Pointer definition of ModelPart.
Serialization
class Serializer
void save (Serializer &rSerializer) const override
void load (Serializer &rSerializer) override
Additional Inherited Members
Static Public Member Functions inherited from Kratos::Flags
static Flags Create (IndexType ThisPosition, bool Value=true)
Detailed Description
ModelPart class.
Detail class definition.
Member Typedef Documentation
typedef MeshType::ConditionConstantIterator Kratos::ModelPart::ConditionConstantIterator
Const iterator over the Conditions. This iterator is an indirect iterator over Conditions::Pointer which turn back a reference to Condition by * operator and not a pointer for more convenient usage.
typedef MeshType::ConditionIterator Kratos::ModelPart::ConditionIterator
Iterator over the Conditions. This iterator is an indirect iterator over Conditions::Pointer which turn back a reference to Condition by * operator and not a pointer for more convenient usage.
typedef MeshType::ConditionsContainerType Kratos::ModelPart::ConditionsContainerType
Condintions container. A vector set of Conditions with their Id's as key.
typedef Condition Kratos::ModelPart::ConditionType
typedef PointerVectorSet<DofType, SetIdentityFunction<DofType>, std::less<SetIdentityFunction<DofType>::result_type>, std::equal_to<SetIdentityFunction<DofType>::result_type>, DofType* > Kratos::ModelPart::DofsArrayType
typedef Dof<double> Kratos::ModelPart::DofType
typedef MeshType::ElementConstantIterator Kratos::ModelPart::ElementConstantIterator
Const iterator over the Elements. This iterator is an indirect iterator over Elements::Pointer which turn back a reference to Element by * operator and not a pointer for more convenient usage.
typedef MeshType::ElementIterator Kratos::ModelPart::ElementIterator
Iterator over the Elements. This iterator is an indirect iterator over Elements::Pointer which turn back a reference to Element by * operator and not a pointer for more convenient usage.
typedef MeshType::ElementsContainerType Kratos::ModelPart::ElementsContainerType
Element container. A vector set of Elements with their Id's as key.
Iterator over the properties. This iterator is an indirect iterator over Properties::Pointer which turn back a reference to properties by * operator and not a pointer for more convenient usage.
typedef Element Kratos::ModelPart::ElementType
typedef std::size_t Kratos::ModelPart::IndexType
typedef PointerVector<MeshType> Kratos::ModelPart::MeshesContainerType
typedef Mesh<NodeType, PropertiesType, ElementType, ConditionType> Kratos::ModelPart::MeshType
typedef MeshType::NodeConstantIterator Kratos::ModelPart::NodeConstantIterator
Const iterator over the nodes. This iterator is an indirect iterator over Node::Pointer which turn back a reference to node by * operator and not a pointer for more convenient usage.
typedef MeshType::NodeIterator Kratos::ModelPart::NodeIterator
Iterator over the nodes. This iterator is an indirect iterator over Node::Pointer which turn back a reference to node by * operator and not a pointer for more convenient usage.
typedef MeshType::NodesContainerType Kratos::ModelPart::NodesContainerType
Nodes container. Which is a vector set of nodes with their Id's as key.
typedef Node< 3 > Kratos::ModelPart::NodeType
typedef MeshType::PropertiesConstantIterator Kratos::ModelPart::PropertiesConstantIterator
Const iterator over the Properties. This iterator is an indirect iterator over Properties::Pointer which turn back a reference to Properties by * operator and not a pointer for more convenient usage.
typedef MeshType::PropertiesContainerType Kratos::ModelPart::PropertiesContainerType
Properties container. Which is a vector set of Properties with their Id's as key.
Iterator over the properties. This iterator is an indirect iterator over Properties::Pointer which turn back a reference to properties by * operator and not a pointer for more convenient usage.
typedef MeshType::PropertiesIterator Kratos::ModelPart::PropertiesIterator
Iterator over the Properties. This iterator is an indirect iterator over Node::Pointer which turn back a reference to node by * operator and not a pointer for more convenient usage.
typedef Properties Kratos::ModelPart::PropertiesType
typedef std::size_t Kratos::ModelPart::SizeType
typedef SubModelPartsContainerType::const_iterator Kratos::ModelPart::SubModelPartConstantIterator
Constant iterator over the sub model parts of this model part.
Note that this iterator only iterates over the next level of sub model parts and does not go through the hierarchy of the sub model parts
typedef SubModelPartsContainerType::iterator Kratos::ModelPart::SubModelPartIterator
Iterator over the sub model parts of this model part.
Note that this iterator only iterates over the next level of sub model parts and does not go through the hierarchy of the sub model parts
typedef PointerHashMapSet<ModelPart, boost::hash< std::string >, GetModelPartName, ModelPart*> Kratos::ModelPart::SubModelPartsContainerType
The container of the sub model parts. A hash table is used.
typedef TablesContainerType::const_iterator Kratos::ModelPart::TableConstantIterator
Const iterator over the Tables. This iterator is an indirect iterator over Tables::Pointer which turn back a reference to Table by * operator and not a pointer for more convenient usage.
typedef TablesContainerType::iterator Kratos::ModelPart::TableIterator
Iterator over the Tables. This iterator is an indirect iterator over Tables::Pointer which turn back a reference to Table by * operator and not a pointer for more convenient usage.
typedef PointerVectorMap<SizeType, TableType> Kratos::ModelPart::TablesContainerType
The container of the tables. A vector map of the tables.
typedef Table<double,double> Kratos::ModelPart::TableType
Defining a table with double argument and result type as table type.
Member Enumeration Documentation
enum Kratos::ModelPart::OwnershipType
Enumerator
Kratos_All
Kratos_Local
Kratos_Ghost
Kratos_Ownership_Size
Constructor & Destructor Documentation
Kratos::ModelPart::ModelPart ()
Default constructor.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Clone(), read_stl::mesh, mMeshes, mName, mpCommunicator, pGetMesh(), and Kratos::PointerVector< TDataType, TPointerType, TContainerType >::push_back().
Referenced by CreateSubModelPart().
Kratos::ModelPart::ModelPart (std::string const & NewName)
Constructor with name.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Clone(), read_stl::mesh, mMeshes, mName, mpCommunicator, pGetMesh(), and Kratos::PointerVector< TDataType, TPointerType, TContainerType >::push_back().
Kratos::ModelPart::ModelPart (std::string const & NewName, IndexType NewBufferSize)
Constructor with name and bufferSize.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Clone(), read_stl::mesh, mMeshes, mName, mpCommunicator, pGetMesh(), and Kratos::PointerVector< TDataType, TPointerType, TContainerType >::push_back().
Kratos::ModelPart::ModelPart (ModelPart const & rOther) explicit
Copy constructor.
References KRATOS_WATCH, mMeshes, and Kratos::PointerVector< TDataType, TPointerType, TContainerType >::size().
Kratos::ModelPart::~ModelPart () override
Destructor.
References Kratos::PointerVector< TDataType, TPointerType, TContainerType >::begin(), Kratos::PointerVector< TDataType, TPointerType, TContainerType >::end(), IsSubModelPart(), mMeshes, mpCommunicator, mpVariablesList, NodesBegin(), NodesEnd(), SubModelPartsBegin(), and SubModelPartsEnd().
Member Function Documentation
void Kratos::ModelPart::AddCondition (ConditionType::Pointer pNewCondition, IndexType ThisIndex = 0)
Inserts a condition in the current mesh.
Inserts a condition in the mesh with ThisIndex.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddCondition(), AddCondition(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Conditions(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::ConditionsEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetMesh(), IsSubModelPart(), KRATOS_ERROR, and mpParentModelPart.
Referenced by AddCondition(), Kratos::Python::AddModelPartToPython(), Kratos::Python::ModelPartAddCondition1(), and Kratos::Python::ModelPartAddCondition2().
void Kratos::ModelPart::AddConditions (std::vector< IndexType > & ConditionIds, IndexType ThisIndex = 0)
Inserts a list of conditions to a submodelpart provided their Id. Does nothing if applied to the top model part
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddCondition(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Conditions(), Conditions(), ConditionsEnd(), Kratos::Condition::Create(), CreateNewCondition(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), Kratos::KratosComponents< TComponentType >::Get(), GetMesh(), GetParentModelPart(), GetRootModelPart(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, mpParentModelPart, pGetNode(), Kratos::PointerVector< TPointType >::push_back(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::push_back(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::reserve(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::Unique().
Referenced by Kratos::Python::AddConditionsByIds(), Kratos::ConnectivityPreserveModeler::DuplicateConditions(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), and Kratos::ModelPartIO::ReadSubModelPartConditionsBlock().
template<class TIteratorType > void Kratos::ModelPart::AddConditions (TIteratorType conditions_begin, TIteratorType conditions_end, IndexType ThisIndex = 0) inline
Inserts a list of pointers to nodes
References Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Conditions(), ConditionsEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetParentModelPart(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::push_back(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::Unique().
void Kratos::ModelPart::AddElement (ElementType::Pointer pNewElement, IndexType ThisIndex = 0)
Inserts a element in the current mesh.
Inserts a element in the mesh with ThisIndex.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddElement(), AddElement(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Elements(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::ElementsEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetMesh(), IsSubModelPart(), KRATOS_ERROR, and mpParentModelPart.
Referenced by AddElement(), and Kratos::Python::AddModelPartToPython().
void Kratos::ModelPart::AddElements (std::vector< IndexType > & ElementIds, IndexType ThisIndex = 0)
Inserts a list of elements to a submodelpart provided their Id. Does nothing if applied to the top model part
Inserts a list of conditions to a submodelpart provided their Id. Does nothing if applied to the top model part
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddElement(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::Element::Create(), CreateNewElement(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Elements(), Elements(), ElementsEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), Kratos::KratosComponents< TComponentType >::Get(), GetMesh(), GetParentModelPart(), GetRootModelPart(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, mpParentModelPart, pGetNode(), pProperties(), Kratos::PointerVector< TPointType >::push_back(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::push_back(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::reserve(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::Unique().
Referenced by Kratos::Python::AddElementsByIds(), Kratos::ConnectivityPreserveModeler::DuplicateElements(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::ModelPartIO::ReadElementsBlock(), and Kratos::ModelPartIO::ReadSubModelPartElementsBlock().
template<class TIteratorType > void Kratos::ModelPart::AddElements (TIteratorType elements_begin, TIteratorType elements_end, IndexType ThisIndex = 0) inline
Inserts a list of pointers to nodes
References Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Elements(), ElementsEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetParentModelPart(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::push_back(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::Unique().
template<typename TEntitiesContainerType > void Kratos::ModelPart::AddEntities (TEntitiesContainerType const & Source, TEntitiesContainerType & rDestination, Flags Options) inline private
template<class TDataType > void Kratos::ModelPart::AddNodalSolutionStepVariable (Variable< TDataType > const & ThisVariable) inline
References KRATOS_ERROR_IF, Kratos::VariableData::Name(), and Kratos::Nodes.
Referenced by Kratos::Python::AddNodalSolutionStepVariable(), Kratos::CuttingUtility::AddSkinConditions(), Kratos::CuttingUtility::Calculate_Coordinate_And_Insert_New_Nodes_Mod(), and Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE().
void Kratos::ModelPart::AddNode (NodeType::Pointer pNewNode, IndexType ThisIndex = 0)
Inserts a node in the current mesh.
Inserts a node in the mesh with ThisIndex.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddNode(), AddNode(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetMesh(), IsSubModelPart(), KRATOS_ERROR, mpParentModelPart, Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Nodes(), and Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::NodesEnd().
Referenced by Kratos::Python::AddModelPartToPython(), AddNode(), and Kratos::StructuredMeshRefinementModeler::GenerateMesh().
void Kratos::ModelPart::AddNodes (std::vector< IndexType > & NodeIds, IndexType ThisIndex = 0)
Inserts a list of nodes in a submodelpart provided their Id. Does nothing if applied to the top model part
References Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetParentModelPart(), GetRootModelPart(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, Nodes(), NodesEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::push_back(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::reserve(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::Unique().
Referenced by Kratos::Python::AddNodesByIds(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::ConnectivityPreserveModeler::DuplicateSubModelParts(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), and Kratos::ModelPartIO::ReadSubModelPartNodesBlock().
template<class TIteratorType > void Kratos::ModelPart::AddNodes (TIteratorType nodes_begin, TIteratorType nodes_end, IndexType ThisIndex = 0) inline
Inserts a list of pointers to nodes
References Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetParentModelPart(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, Nodes(), NodesEnd(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::push_back(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::Unique().
void Kratos::ModelPart::AddProperties (PropertiesType::Pointer pNewProperties, IndexType ThisIndex = 0)
Inserts a properties in the current mesh.
Inserts a properties in the mesh with ThisIndex.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddProperties(), AddProperties(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetMesh(), IsSubModelPart(), KRATOS_ERROR, mpParentModelPart, Name(), and Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Properties().
Referenced by AddProperties(), Kratos::Python::ModelPartAddProperties1(), Kratos::Python::ModelPartAddProperties2(), and Kratos::ModelPartIO::ReadSubModelPartPropertiesBlock().
void Kratos::ModelPart::AddSubModelPart (ModelPart & rThisSubModelPart)
Add an existing model part as a sub model part. All the meshes will be added to the parents. NOTE: The added sub model part should not have mesh entities with id in conflict with other ones in the parent In the case of conflict the new one would replace the old one resulting inconsitency in parent.
References AddSubModelPart(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::end(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::find(), IsSubModelPart(), KRATOS_ERROR, mpParentModelPart, mSubModelParts, Name(), and SetParentModelPart().
Referenced by AddSubModelPart().
void Kratos::ModelPart::AddTable (IndexType TableId, TableType::Pointer pNewTable)
Inserts a Table
References AddTable(), Kratos::PointerVectorMap< TKeyType, TDataType, TCompareType, TPointerType, TContainerType >::insert(), IsSubModelPart(), mpParentModelPart, and mTables.
Referenced by Kratos::Python::AddModelPartToPython(), AddTable(), and Kratos::ModelPartIO::ReadSubModelPartTablesBlock().
void Kratos::ModelPart::AssignNode (NodeType::Pointer pThisNode, IndexType ThisIndex = 0)
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddNode(), AssignNode(), GetMesh(), IsSubModelPart(), mBufferSize, mpParentModelPart, and mpVariablesList.
Referenced by AssignNode().
int Kratos::ModelPart::Check (ProcessInfo & rCurrentProcessInfo) const virtual
run input validation
References ConditionsBegin(), ConditionsEnd(), ElementsBegin(), ElementsEnd(), KRATOS_CATCH, and KRATOS_TRY.
Referenced by Kratos::Python::AddModelPartToPython().
ModelPart::IndexType Kratos::ModelPart::CloneSolutionStep ()
References IsSubModelPart(), KRATOS_ERROR, mBufferSize, mpParentModelPart, mpProcessInfo, Name(), Nodes(), NodesBegin(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::size().
Referenced by Kratos::Python::AddModelPartToPython(), and CloneTimeStep().
ModelPart::IndexType Kratos::ModelPart::CloneTimeStep ()
References CloneSolutionStep(), IsSubModelPart(), KRATOS_THROW_ERROR, mpProcessInfo, and Name().
Referenced by Kratos::Python::AddModelPartToPython().
ModelPart::IndexType Kratos::ModelPart::CloneTimeStep (double NewTime)
References CloneSolutionStep(), IsSubModelPart(), KRATOS_THROW_ERROR, mpProcessInfo, and Name().
ConditionsContainerType& Kratos::ModelPart::Conditions (IndexType ThisIndex = 0) inline
Referenced by Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), AddConditions(), Kratos::CuttingUtility::AddSkinConditions(), Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::Build(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildLHS(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildLHS_CompleteOnFreeRows(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildRHS(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildRHSNoDirichlet(), Kratos::NormalCalculationUtils::CalculateOnSimplex(), Kratos::FindConditionsNeighboursProcess::ClearNeighbours(), Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::ReorderAndOptimizeModelPartProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::FindConditionsNeighboursProcess::Execute(), Kratos::ReplaceElementsAndConditionsProcess::Execute(), Kratos::CheckSkinProcess::Execute(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeNonLinIteration(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::StructuredMeshRefinementModeler::GenerateConditions(), Kratos::CuttingUtility::GenerateElements(), Kratos::StructuredMeshRefinementModeler::GenerateMesh(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::CalculateSignedDistanceTo3DSkinProcess::GenerateSkinModelPart(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeConditions(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::InitializeConditions(), Kratos::ResidualBasedIncrementalUpdateStaticScheme< TSparseSpace, TDenseSpace >::InitializeNonLinIteration(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::InitializeNonLinIteration(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeSolutionStep(), Kratos::ReorderAndOptimizeModelPartProcess::OptimizeOrdering(), Kratos::ModelPartIO::ReadConditionsBlock(), Kratos::ModelPartIO::ReadInitialValues(), Kratos::ModelPartIO::ReadMeshConditionsBlock(), Kratos::ModelPartIO::ReadModelPart(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::ScalarBuildComponent(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ReplaceElementsAndConditionsProcess::UpdateSubModelPart(), Kratos::BoundingVolumeTree::UpdateTree(), and Kratos::ModelPartIO::WriteSubModelPartBlock().
ConditionsContainerType::ContainerType& Kratos::ModelPart::ConditionsArray (IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::AddModelPartToPython().
ConditionIterator Kratos::ModelPart::ConditionsBegin (IndexType ThisIndex = 0) inline
Referenced by Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), Kratos::IsosurfacePrinterApplication::AddSkinConditions(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::NormalCalculationUtils::CalculateOnSimplex(), Kratos::NormalCalculationUtils::CalculateOnSimplexLowMemory(), Kratos::Scheme< TSparseSpace, TDenseSpace >::Check(), Check(), Kratos::ConnectivityPreserveModeler::DuplicateConditions(), Kratos::ReorderAndOptimizeModelPartProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::ReplaceElementsAndConditionsProcess::Execute(), Kratos::CheckSkinProcess::Execute(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeConditions(), Kratos::ReorderAndOptimizeModelPartProcess::OptimizeOrdering(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::VariableUtils::SumConditionScalarVariable(), Kratos::VariableUtils::SumConditionVectorVariable(), Kratos::NormalCalculationUtils::SwapNormals(), and Kratos::ReplaceElementsAndConditionsProcess::UpdateSubModelPart().
ConditionConstantIterator Kratos::ModelPart::ConditionsBegin (IndexType ThisIndex = 0) const inline
ConditionIterator Kratos::ModelPart::ConditionsEnd (IndexType ThisIndex = 0) inline
Referenced by AddConditions(), Kratos::IsosurfacePrinterApplication::AddSkinConditions(), Kratos::NormalCalculationUtils::CalculateOnSimplex(), Kratos::NormalCalculationUtils::CalculateOnSimplexLowMemory(), Kratos::SolvingStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Check(), Kratos::Scheme< TSparseSpace, TDenseSpace >::Check(), Check(), Kratos::ConnectivityPreserveModeler::DuplicateConditions(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::CheckSkinProcess::Execute(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), and Kratos::NormalCalculationUtils::SwapNormals().
ConditionConstantIterator Kratos::ModelPart::ConditionsEnd (IndexType ThisIndex = 0) const inline
ConditionType::Pointer Kratos::ModelPart::CreateNewCondition (std::string ConditionName, IndexType Id, std::vector< IndexType > ConditionNodeIds, PropertiesType::Pointer pProperties, IndexType ThisIndex = 0)
Inserts a condition in the current mesh.
Referenced by AddConditions(), Kratos::KratosJsonIO::FillModelPart(), and Kratos::Python::ModelPartCreateNewCondition().
ConditionType::Pointer Kratos::ModelPart::CreateNewCondition (std::string ConditionName, IndexType Id, Geometry< Node< 3 > >::PointsArrayType pConditionNodes, PropertiesType::Pointer pProperties, IndexType ThisIndex = 0)
Inserts a condition in the current mesh.
ElementType::Pointer Kratos::ModelPart::CreateNewElement (std::string ElementName, IndexType Id, std::vector< IndexType > ElementNodeIds, PropertiesType::Pointer pProperties, IndexType ThisIndex = 0)
Inserts an element in the current mesh.
Referenced by AddElements(), Kratos::StructuredMeshGeneratorProcess::CreateCellTetrahedra(), Kratos::KratosJsonIO::FillModelPart(), Kratos::StructuredMeshGeneratorProcess::GenerateTriangularElements(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), and Kratos::Python::ModelPartCreateNewElement().
ElementType::Pointer Kratos::ModelPart::CreateNewElement (std::string ElementName, IndexType Id, Geometry< Node< 3 > >::PointsArrayType pElementNodes, PropertiesType::Pointer pProperties, IndexType ThisIndex = 0)
Inserts an element in the current mesh.
ModelPart::NodeType::Pointer Kratos::ModelPart::CreateNewNode (int Id, double x, double y, double z, VariablesList * pNewVariablesList, ModelPart::IndexType ThisIndex = 0)
Inserts a node in the current mesh.
Inserts a node in the mesh with ThisIndex.
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddNode(), CreateNewNode(), GetMesh(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, mBufferSize, mpParentModelPart, and Nodes().
Referenced by Kratos::CuttingUtility::AddSkinConditions(), Kratos::CuttingUtility::Calculate_Coordinate_And_Insert_New_Nodes_Mod(), CreateNewNode(), Kratos::KratosJsonIO::FillModelPart(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::GeometryTesterUtility::GenerateNodes(), Kratos::StructuredMeshRefinementModeler::GenerateNodes(), Kratos::CartesianMeshGeneratorModeler::GenerateNodes(), Kratos::StructuredMeshGeneratorProcess::GenerateNodes2D(), Kratos::StructuredMeshGeneratorProcess::GenerateNodes3D(), Kratos::CalculateSignedDistanceTo3DSkinProcess::GenerateSkinModelPart(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::Python::ModelPartCreateNewNode(), and Kratos::ModelPartIO::ReadNodesBlock().
ModelPart::NodeType::Pointer Kratos::ModelPart::CreateNewNode (ModelPart::IndexType Id, double x, double y, double z, ModelPart::IndexType ThisIndex = 0)
References CreateNewNode(), and mpVariablesList.
ModelPart::NodeType::Pointer Kratos::ModelPart::CreateNewNode (ModelPart::IndexType Id, double x, double y, double z, double * pThisData, ModelPart::IndexType ThisIndex = 0)
References Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::AddNode(), CreateNewNode(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::find(), GetMesh(), IsSubModelPart(), KRATOS_CATCH, KRATOS_ERROR, KRATOS_TRY, mBufferSize, mpParentModelPart, mpVariablesList, Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::Nodes(), and NodesEnd().
ModelPart::NodeType::Pointer Kratos::ModelPart::CreateNewNode (ModelPart::IndexType NodeId, ModelPart::NodeType const & rSourceNode, ModelPart::IndexType ThisIndex = 0)
References CreateNewNode(), mpVariablesList, Kratos::Point::X(), Kratos::Point::Y(), and Kratos::Point::Z().
ModelPart::IndexType Kratos::ModelPart::CreateSolutionStep ()
References KRATOS_THROW_ERROR.
Referenced by Kratos::Python::AddModelPartToPython(), and CreateTimeStep().
ModelPart & Kratos::ModelPart::CreateSubModelPart (std::string const & NewSubModelPartName)
Creates a new sub model part with given name. Does nothing if a sub model part with the same name exist.
References Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::end(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::find(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::insert(), KRATOS_THROW_ERROR, mBufferSize, ModelPart(), mpProcessInfo, mpVariablesList, mSubModelParts, and SetParentModelPart().
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ConnectivityPreserveModeler::DuplicateSubModelParts(), Kratos::StructuredMeshGeneratorProcess::Execute(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), and Kratos::ModelPartIO::ReadSubModelPartBlock().
ModelPart::IndexType Kratos::ModelPart::CreateTimeStep (double NewTime)
References CreateSolutionStep(), IsSubModelPart(), KRATOS_THROW_ERROR, mpProcessInfo, and Name().
Referenced by Kratos::Python::AddModelPartToPython().
ElementsContainerType& Kratos::ModelPart::Elements (IndexType ThisIndex = 0) inline
Referenced by Kratos::ParallelDistanceCalculator< TDim >::AbsDistancesOnDividedElements(), Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), AddElements(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurface(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurfaceAndHigher(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurfaceAndLower(), Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::Build(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildLHS(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildLHS_CompleteOnFreeRows(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildRHS(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildRHSNoDirichlet(), Kratos::BodyNormalCalculationUtils::CalculateBodyNormals(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances2D(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances3D(), Kratos::ParallelDistanceCalculator< TDim >::CalculateDistancesLagrangianSurface(), Kratos::ParallelDistanceCalculator< TDim >::CalculateExactDistancesOnDividedElements(), Kratos::CalculateDistanceToSkinProcess::CalculateNodalDistances(), Kratos::FindElementalNeighboursProcess::ClearNeighbours(), Kratos::EdgeSwapping2DModeler::CollapseNodes(), Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::ParticleConvectUtily< TDim >::EraseOuterElements(), Kratos::ReorderAndOptimizeModelPartProcess::Execute(), Kratos::FindNodalHProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::Execute(), Kratos::FindNodalNeighboursProcess::Execute(), Kratos::ReplaceElementsAndConditionsProcess::Execute(), Kratos::FindElementalNeighboursProcess::Execute(), Kratos::CheckSkinProcess::Execute(), Kratos::ParallelDistanceCalculator< TDim >::ExtendDistancesByLayer(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeNonLinIteration(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::CuttingUtility::FindSmallestEdge(), Kratos::CuttingUtility::FirstLoop(), Kratos::CuttingUtility::GenerateCut(), Kratos::StructuredMeshRefinementModeler::GenerateElements(), Kratos::CuttingUtility::GenerateElements(), Kratos::StructuredMeshRefinementModeler::GenerateMesh(), Kratos::MeshSuiteModeler::GenerateMesh(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeElements(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::InitializeElements(), Kratos::ResidualBasedIncrementalUpdateStaticScheme< TSparseSpace, TDenseSpace >::InitializeNonLinIteration(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::InitializeNonLinIteration(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeSolutionStep(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::LevelSetConvectionProcess< TDim >::LevelSetConvectionProcess(), Kratos::ReorderAndOptimizeModelPartProcess::OptimizeOrdering(), Kratos::ModelPartIO::ReadInitialValues(), Kratos::ModelPartIO::ReadMeshElementsBlock(), Kratos::ModelPartIO::ReadModelPart(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::MeshSuiteModeler::ReGenerateMesh(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::ScalarBuildComponent(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ReplaceElementsAndConditionsProcess::UpdateSubModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::VariationalDistanceCalculationProcess(), and Kratos::ModelPartIO::WriteSubModelPartBlock().
ElementsContainerType::ContainerType& Kratos::ModelPart::ElementsArray (IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::EdgeSwapping2DModeler::CollapseNodes(), Kratos::FindIntersectedGeometricalObjectsProcess::FindIntersectedSkinObjects(), Kratos::EdgeSwapping2DModeler::FindNodalNeighbours(), Kratos::CartesianMeshGeneratorModeler::GenerateMesh(), Kratos::EdgeSwapping2DModeler::MarkBadQualityElements(), Kratos::EdgeSwapping2DModeler::Remesh(), Kratos::EdgeSwapping2DModeler::SetNodalCollapsingData(), Kratos::EdgeSwapping2DModeler::SetSwappingData(), Kratos::BinBasedFastPointLocator< TDim >::UpdateSearchDatabase(), and Kratos::BinBasedFastPointLocator< TDim >::UpdateSearchDatabaseAssignedSize().
ElementIterator Kratos::ModelPart::ElementsBegin (IndexType ThisIndex = 0) inline
Referenced by Kratos::ParallelDistanceCalculator< TDim >::AbsDistancesOnDividedElements(), Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::CartesianMeshGeneratorModeler::CalculateBoundaryIntersections(), Kratos::CartesianMeshGeneratorModeler::CalculateBoundingBox(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances2D(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances3D(), Kratos::ParallelDistanceCalculator< TDim >::CalculateDistancesLagrangianSurface(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::CalculateEmbeddedVelocity(), Kratos::ParallelDistanceCalculator< TDim >::CalculateExactDistancesOnDividedElements(), Kratos::CartesianMeshGeneratorModeler::CalculateNormals(), Kratos::Scheme< TSparseSpace, TDenseSpace >::Check(), Check(), Kratos::ConnectivityPreserveModeler::DuplicateElements(), Kratos::ParticleConvectUtily< TDim >::EraseOuterElements(), Kratos::MeasureMeshQualityProcess::Execute(), Kratos::TetrahedraMeshEdgeSwappingProcess::Execute(), Kratos::ReorderAndOptimizeModelPartProcess::Execute(), Kratos::FindNodalHProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::Execute(), Kratos::CalculateNodalAreaProcess::Execute(), Kratos::ReplaceElementsAndConditionsProcess::Execute(), Kratos::FindIntersectedGeometricalObjectsProcess::Execute(), Kratos::ParallelDistanceCalculator< TDim >::ExtendDistancesByLayer(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::ParallelDistanceCalculator< TDim >::FindMaximumEdgeSize(), Kratos::CartesianMeshGeneratorModeler::GenerateMesh(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::FindIntersectedGeometricalObjectsProcess::GenerateOctree(), Kratos::CalculateDiscontinuousDistanceToSkinProcess::Initialize(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeElements(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::LevelSetConvectionProcess< TDim >::LevelSetConvectionProcess(), Kratos::ReorderAndOptimizeModelPartProcess::OptimizeOrdering(), Kratos::MeshSmoothingProcess::PerformSmoothing(), Kratos::EdgeSwapping2DModeler::PrepareForSwapping(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::ConnectivityPreserveModeler::ResetModelPart(), Kratos::MeshLocalSmoothingProcess::SelectLowQualityElementNodes(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::SetMaximumAndMinimumDistanceValues(), Kratos::MeshSuiteModeler::SetMesh(), Kratos::VariableUtils::SumElementScalarVariable(), Kratos::VariableUtils::SumElementVectorVariable(), Kratos::ReplaceElementsAndConditionsProcess::UpdateSubModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::VariationalDistanceCalculationProcess(), and Kratos::EdgeSwapping2DModeler::WriteMesh().
ElementConstantIterator Kratos::ModelPart::ElementsBegin (IndexType ThisIndex = 0) const inline
ElementIterator Kratos::ModelPart::ElementsEnd (IndexType ThisIndex = 0) inline
Referenced by AddElements(), Kratos::CartesianMeshGeneratorModeler::CalculateBoundaryIntersections(), Kratos::CartesianMeshGeneratorModeler::CalculateBoundingBox(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances2D(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances3D(), Kratos::CartesianMeshGeneratorModeler::CalculateNormals(), Kratos::SolvingStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Check(), Kratos::Scheme< TSparseSpace, TDenseSpace >::Check(), Check(), Kratos::ConnectivityPreserveModeler::DuplicateElements(), Kratos::ParticleConvectUtily< TDim >::EraseOuterElements(), Kratos::MeasureMeshQualityProcess::Execute(), Kratos::TetrahedraMeshEdgeSwappingProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::CalculateNodalAreaProcess::Execute(), Kratos::ParallelDistanceCalculator< TDim >::FindMaximumEdgeSize(), Kratos::CartesianMeshGeneratorModeler::GenerateMesh(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::FindIntersectedGeometricalObjectsProcess::GenerateOctree(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::MeshSmoothingProcess::PerformSmoothing(), Kratos::EdgeSwapping2DModeler::PrepareForSwapping(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::ConnectivityPreserveModeler::ResetModelPart(), Kratos::MeshLocalSmoothingProcess::SelectLowQualityElementNodes(), Kratos::MeshSuiteModeler::SetMesh(), and Kratos::EdgeSwapping2DModeler::WriteMesh().
ElementConstantIterator Kratos::ModelPart::ElementsEnd (IndexType ThisIndex = 0) const inline
IndexType Kratos::ModelPart::GetBufferSize () inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::Check(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), and Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart().
Communicator& Kratos::ModelPart::GetCommunicator () inline
Referenced by Kratos::ParallelDistanceCalculator< TDim >::AbsDistancesOnDividedElements(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildAndSolve(), Kratos::BodyNormalCalculationUtils::CalculateBodyNormals(), Kratos::ParallelDistanceCalculator< TDim >::CalculateDistancesLagrangianSurface(), Kratos::ParallelDistanceCalculator< TDim >::CalculateExactDistancesOnDividedElements(), Kratos::NormalCalculationUtils::CalculateOnSimplex(), Kratos::NormalCalculationUtils::CalculateOnSimplexLowMemory(), Kratos::ParallelDistanceCalculator< TDim >::Check(), Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::FindNodalHProcess::Execute(), Kratos::CalculateNodalAreaProcess::Execute(), Kratos::ParallelDistanceCalculator< TDim >::ExtendDistancesByLayer(), Kratos::ParallelDistanceCalculator< TDim >::FindMaximumEdgeSize(), Kratos::ResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Initialize(), Kratos::ResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::InitializeSolutionStep(), Kratos::ResidualBasedLinearStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::InitializeSolutionStep(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::Python::ModelPartGetCommunicator(), Kratos::DisplacementCriteria< TSparseSpace, TDenseSpace >::PostCriteria(), Kratos::ResidualCriteria< TSparseSpace, TDenseSpace >::PostCriteria(), Kratos::ModelPartIO::ReadModelPart(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::SpatialSearch::SearchConditionsInRadiusExclusive(), Kratos::SpatialSearch::SearchConditionsInRadiusInclusive(), Kratos::SpatialSearch::SearchConditionsOverElementsInRadiusExclusive(), Kratos::SpatialSearch::SearchConditionsOverElementsInRadiusInclusive(), Kratos::SpatialSearch::SearchElementsInRadiusExclusive(), Kratos::SpatialSearch::SearchElementsInRadiusInclusive(), Kratos::SpatialSearch::SearchElementsOverConditionsInRadiusExclusive(), Kratos::SpatialSearch::SearchElementsOverConditionsInRadiusInclusive(), Kratos::SpatialSearch::SearchNodesInRadiusExclusive(), Kratos::SpatialSearch::SearchNodesInRadiusInclusive(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ResidualBasedLinearStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Solve(), Kratos::ResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::SolveSolutionStep(), Kratos::VariableUtils::SumConditionScalarVariable(), Kratos::VariableUtils::SumConditionVectorVariable(), Kratos::VariableUtils::SumElementScalarVariable(), Kratos::VariableUtils::SumElementVectorVariable(), Kratos::VariableUtils::SumHistoricalNodeScalarVariable(), Kratos::VariableUtils::SumHistoricalNodeVectorVariable(), Kratos::VariableUtils::SumNonHistoricalNodeScalarVariable(), and Kratos::VariableUtils::SumNonHistoricalNodeVectorVariable().
Communicator const& Kratos::ModelPart::GetCommunicator () const inline
ConditionType& Kratos::ModelPart::GetCondition (IndexType ConditionId, IndexType ThisIndex = 0) inline
Returns a reference condition corresponding to it's identifier
ElementType& Kratos::ModelPart::GetElement (IndexType ElementId, IndexType ThisIndex = 0) inline
Returns a reference element corresponding to it's identifier
Referenced by Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE().
MeshType& Kratos::ModelPart::GetMesh (IndexType ThisIndex = 0) inline
Referenced by AddCondition(), AddConditions(), AddElement(), AddElements(), AddNode(), AddProperties(), Kratos::CuttingUtility::AddSkinConditions(), AssignNode(), CreateNewNode(), Kratos::TranslationOperation::ExecuteInitializeSolutionStep(), Kratos::RotationOperation::ExecuteInitializeSolutionStep(), Kratos::KratosJsonIO::FillModelPart(), Kratos::CuttingUtility::GenerateElements(), Kratos::MeshSuiteModeler::GenerateMesh(), Kratos::ApplyConstantVectorValueProcess::InternalApplyValue(), Kratos::ApplyConstantScalarValueProcess::InternalApplyValue(), Kratos::ApplyConstantScalarValueProcess::InternalApplyValueWithoutFixing(), Kratos::AssignScalarVariableToConditionsProcess::InternalAssignValue(), Kratos::AssignScalarFieldToConditionsProcess::InternalAssignValue(), Kratos::AssignScalarFieldToConditionsProcess::InternalAssignValueComponents(), Kratos::AssignScalarVariableToConditionsProcess::InternalAssignValueSerial(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::MeshSmoothingProcess::PerformSmoothing(), PrintData(), Kratos::ModelPartIO::ReadMeshBlock(), Kratos::DatafileIO::ReadModelPart(), Kratos::MeshSuiteModeler::ReGenerateMesh(), RemoveCondition(), RemoveElement(), RemoveNode(), RemoveProperties(), and Kratos::ModelPartIO::WriteModelPart().
MeshType const& Kratos::ModelPart::GetMesh (IndexType ThisIndex = 0) const inline
MeshesContainerType& Kratos::ModelPart::GetMeshes () inline
Referenced by Kratos::KratosJsonIO::FillModelPart(), Kratos::Python::ModelPartGetMesh2(), Kratos::MeshSmoothingProcess::PerformSmoothing(), Kratos::ModelPartIO::ReadMeshBlock(), RemoveConditions(), RemoveElements(), and RemoveNodes().
MeshesContainerType const& Kratos::ModelPart::GetMeshes () const inline
SizeType Kratos::ModelPart::GetNodalSolutionStepDataSize () inline
Referenced by Kratos::Python::AddModelPartToPython(), and Kratos::CuttingUtility::UpdateCutData().
SizeType Kratos::ModelPart::GetNodalSolutionStepTotalDataSize () inline
Referenced by Kratos::Python::AddModelPartToPython().
VariablesList& Kratos::ModelPart::GetNodalSolutionStepVariablesList () inline
Referenced by Kratos::CuttingUtility::AddSkinConditions(), Kratos::ApplyConstantScalarValueProcess::ApplyConstantScalarValueProcess(), Kratos::ApplyConstantVectorValueProcess::ApplyConstantVectorValueProcess(), Kratos::CuttingUtility::Calculate_Coordinate_And_Insert_New_Nodes_Mod(), Kratos::KratosJsonIO::CheckAndAssignNodalComponentValue(), Kratos::KratosJsonIO::CheckAndAssignNodalValue(), Kratos::KratosJsonIO::CheckAndAssignNodalValue_ErrorIfFixed(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::ComputeNodalGradientProcess(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::ModelPartIO::ReadNodalDataBlock(), and Kratos::ModelPartIO::WriteNodalDataBlock().
NodeType& Kratos::ModelPart::GetNode (IndexType NodeId, IndexType ThisIndex = 0) inline
Returns a reference node corresponding to it's identifier
Referenced by Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE().
ModelPart* Kratos::ModelPart::GetParentModelPart () const inline
Referenced by AddConditions(), AddElements(), AddNodes(), and Kratos::ReplaceElementsAndConditionsProcess::ObtainRootModelPart().
ProcessInfo& Kratos::ModelPart::GetProcessInfo () inline
Referenced by Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::Build(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::Build(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildLHS(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildLHS_CompleteOnFreeRows(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildRHS(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::BuildRHSNoDirichlet(), Kratos::Scheme< TSparseSpace, TDenseSpace >::Check(), Kratos::AdaptiveResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::CyclicSolve(), Kratos::ResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::EchoInfo(), Kratos::AssignScalarFieldToConditionsProcess::Execute(), Kratos::ComputeBDFCoefficientsProcess::Execute(), Kratos::TranslationOperation::ExecuteInitializeSolutionStep(), Kratos::RotationOperation::ExecuteInitializeSolutionStep(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeNonLinIteration(), Kratos::Scheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::FinalizeSolutionStep(), Kratos::Python::GetProcessInfo(), Kratos::ResidualBasedIncrementalUpdateStaticScheme< TSparseSpace, TDenseSpace >::InitializeNonLinIteration(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::InitializeNonLinIteration(), Kratos::Scheme< TSparseSpace, TDenseSpace >::InitializeSolutionStep(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::InitializeSolutionStep(), Kratos::ResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::InitializeSolutionStep(), Kratos::LevelSetConvectionProcess< TDim >::LevelSetConvectionProcess(), Kratos::ParticleConvectUtily< TDim >::MoveParticles_RK4(), Kratos::ParticleConvectUtily< TDim >::MoveParticles_Substepping(), Kratos::DisplacementCriteria< TSparseSpace, TDenseSpace >::PostCriteria(), Kratos::ResidualCriteria< TSparseSpace, TDenseSpace >::PostCriteria(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::Predict(), Kratos::GidGaussPointsContainer::PrintResults(), ReduceTimeStep(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::ScalarBuildComponent(), Kratos::ResidualBasedBlockBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolver< TSparseSpace, TDenseSpace, TLinearSolver >::SetUpDofSet(), Kratos::ResidualBasedLinearStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Solve(), Kratos::AdaptiveResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Solve(), and Kratos::ResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::SolveSolutionStep().
ProcessInfo const& Kratos::ModelPart::GetProcessInfo () const inline
PropertiesType& Kratos::ModelPart::GetProperties (IndexType PropertiesId, IndexType ThisIndex = 0) inline
Returns a reference Properties corresponding to it's identifier
References Kratos::Properties::Properties().
ModelPart & Kratos::ModelPart::GetRootModelPart ()
this function gives back the "root" model part, that is the model_part that has no father
References GetRootModelPart(), IsSubModelPart(), and mpParentModelPart.
Referenced by AddConditions(), AddElements(), Kratos::Model::AddModelPart(), Kratos::Python::AddModelPartToPython(), AddNodes(), GetRootModelPart(), RemoveConditionsFromAllLevels(), RemoveElementsFromAllLevels(), and RemoveNodesFromAllLevels().
ModelPart& Kratos::ModelPart::GetSubModelPart (std::string const & SubModelPartName) inline
Returns a reference to the sub_model part with given string name In debug gives an error if does not exist.
References KRATOS_THROW_ERROR.
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::StructuredMeshGeneratorProcess::GenerateNodes2D(), Kratos::StructuredMeshGeneratorProcess::GenerateNodes3D(), Kratos::Model::GetModelPart(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), and Kratos::ModelPartIO::WriteSubModelPartBlock().
std::vector< std::string > Kratos::ModelPart::GetSubModelPartNames ()
References Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::begin(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::end(), and mSubModelParts.
Referenced by Kratos::ModelPartIO::WriteSubModelPartBlock().
TableType& Kratos::ModelPart::GetTable (IndexType TableId) inline
Returns a reference to Table corresponding to the identifier
Referenced by Kratos::TranslationOperation::ExecuteInitializeSolutionStep(), and Kratos::RotationOperation::ExecuteInitializeSolutionStep().
bool Kratos::ModelPart::HasSubModelPart (std::string const & ThisSubModelPartName) inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::Model::GetModelPart(), and Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE().
std::string Kratos::ModelPart::Info () const override virtual
Turn back information as a string.
Reimplemented from Kratos::DataValueContainer.
References mName.
Referenced by PrintInfo().
bool Kratos::ModelPart::IsSubModelPart () const inline
Referenced by AddCondition(), AddConditions(), AddElement(), AddElements(), Kratos::Python::AddModelPartToPython(), AddNode(), AddNodes(), AddProperties(), AddSubModelPart(), AddTable(), AssignNode(), CloneSolutionStep(), CloneTimeStep(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), CreateNewNode(), CreateTimeStep(), GetRootModelPart(), Kratos::ReplaceElementsAndConditionsProcess::ObtainRootModelPart(), OverwriteSolutionStepData(), PrintData(), ReduceTimeStep(), RemoveConditionFromAllLevels(), RemoveElementFromAllLevels(), RemoveNodeFromAllLevels(), RemovePropertiesFromAllLevels(), RemoveTableFromAllLevels(), SetBufferSize(), SetNodalSolutionStepVariablesList(), and ~ModelPart().
Kratos::ModelPart::KRATOS_CLASS_POINTER_DEFINITION (ModelPart)
Pointer definition of ModelPart.
Kratos::ModelPart::KRATOS_DEFINE_LOCAL_FLAG (ALL_ENTITIES)
Kratos::ModelPart::KRATOS_DEFINE_LOCAL_FLAG (OVERWRITE_ENTITIES)
void Kratos::ModelPart::load (Serializer & rSerializer) override private virtual
Reimplemented from Kratos::DataValueContainer.
References KRATOS_SERIALIZE_LOAD_BASE_CLASS, Kratos::Serializer::load(), mBufferSize, mMeshes, mName, mpProcessInfo, mpVariablesList, mSubModelParts, SubModelPartsBegin(), and SubModelPartsEnd().
std::string& Kratos::ModelPart::Name () inline
Referenced by Kratos::Model::AddModelPart(), AddProperties(), AddSubModelPart(), CloneSolutionStep(), CloneTimeStep(), CreateTimeStep(), Kratos::Python::GetModelPartName(), Kratos::ModelPart::GetModelPartName::operator()(), OverwriteSolutionStepData(), Kratos::ModelPartIO::ReadNodalDataBlock(), ReduceTimeStep(), RemoveSubModelPart(), SetBufferSize(), Kratos::Python::SetModelPartName(), and SetNodalSolutionStepVariablesList().
std::string const& Kratos::ModelPart::Name () const inline
NodesContainerType& Kratos::ModelPart::Nodes (IndexType ThisIndex = 0) inline
Referenced by Kratos::ParallelDistanceCalculator< TDim >::AbsDistancesOnDividedElements(), Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), AddNodes(), Kratos::IsosurfacePrinterApplication::AddSkinConditions(), Kratos::CuttingUtility::AddSkinConditions(), Kratos::ParallelDistanceCalculator< TDim >::AssignDistanceSign(), Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::Build(), Kratos::CuttingUtility::Calculate_Coordinate_And_Insert_New_Nodes_Mod(), Kratos::ParallelDistanceCalculator< TDim >::CalculateDistancesLagrangianSurface(), Kratos::ParallelDistanceCalculator< TDim >::CalculateExactDistancesOnDividedElements(), Kratos::KratosJsonIO::CheckAndAssignNodalComponentValue(), Kratos::KratosJsonIO::CheckAndAssignNodalValue(), Kratos::KratosJsonIO::CheckAndAssignNodalValue_ErrorIfFixed(), Kratos::VariableUtils::CheckDofs(), Kratos::IsosurfacePrinterApplication::ClearData(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::ClearGradient(), Kratos::FindNodalNeighboursProcess::ClearNeighbours(), Kratos::FindConditionsNeighboursProcess::ClearNeighbours(), Kratos::FindElementalNeighboursProcess::ClearNeighbours(), CloneSolutionStep(), Kratos::CuttingUtility::Create_List_Of_New_Nodes_Mod(), CreateNewNode(), Kratos::SimpleMortarMapperProcess< TDim, TNumNodes, TVarType, THist >::CreateSlaveConectivityDatabase(), Kratos::CuttingUtility::CSR_Row_Matrix_Mod(), Kratos::ReorderAndOptimizeModelPartProcess::Execute(), Kratos::FindNodalHProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::EliminateIsolatedNodesProcess::Execute(), Kratos::FindNodalNeighboursProcess::Execute(), Kratos::FindConditionsNeighboursProcess::Execute(), Kratos::FindElementalNeighboursProcess::Execute(), Kratos::ParallelDistanceCalculator< TDim >::ExtendDistancesByLayer(), Kratos::SignedDistanceCalculationUtils< TDim >::FindMaximumEdgeSize(), Kratos::CuttingUtility::GenerateElements(), Kratos::StructuredMeshRefinementModeler::GenerateMesh(), Kratos::MeshSuiteModeler::GenerateMesh(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::CalculateSignedDistanceTo3DSkinProcess::GenerateSkinModelPart(), Kratos::SimpleMortarMapperProcess< TDim, TNumNodes, TVarType, THist >::GetSystemSize(), Kratos::CalculateDistanceToSkinProcess::InitializeNodalDistances(), Kratos::IsosurfacePrinterApplication::IsosurfacePrinterApplication(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::LevelSetConvectionProcess< TDim >::LevelSetConvectionProcess(), Kratos::SolvingStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::MoveMesh(), Kratos::ParticleConvectUtily< TDim >::MoveParticles_RK4(), Kratos::ParticleConvectUtily< TDim >::MoveParticles_Substepping(), Kratos::ReorderAndOptimizeModelPartProcess::OptimizeOrdering(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::PonderateGradient(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::Predict(), Kratos::AMGCLSolver< TSparseSpaceType, TDenseSpaceType, TReordererType >::ProvideAdditionalData(), Kratos::ModelPartIO::ReadConditionsBlock(), Kratos::ModelPartIO::ReadElementsBlock(), Kratos::ModelPartIO::ReadMeshNodesBlock(), Kratos::ModelPartIO::ReadModelPart(), Kratos::ModelPartIO::ReadNodalDataBlock(), Kratos::ModelPartIO::ReadNodesBlock(), Kratos::CoordinateTransformationUtils< LocalSystemMatrixType, LocalSystemVectorType, double >::RecoverVelocities(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::MeshSuiteModeler::ReGenerateMesh(), Kratos::SimpleMortarMapperProcess< TDim, TNumNodes, TVarType, THist >::ResetNodalArea(), Kratos::ParallelDistanceCalculator< TDim >::ResetVariables(), Kratos::CoordinateTransformationUtils< LocalSystemMatrixType, LocalSystemVectorType, double >::RotateVelocities(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::ScalarBuildComponent(), SetBufferSize(), Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::SetUpDofSet(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::Update(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::VariationalDistanceCalculationProcess(), Kratos::ModelPartIO::WriteNodalDataBlock(), and Kratos::ModelPartIO::WriteSubModelPartBlock().
NodesContainerType::ContainerType& Kratos::ModelPart::NodesArray (IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::EdgeSwapping2DModeler::CollapseNodes(), Kratos::CartesianMeshGeneratorModeler::GenerateMesh(), Kratos::EdgeSwapping2DModeler::Remesh(), Kratos::EdgeSwapping2DModeler::SetCollapsingData(), and Kratos::EdgeSwapping2DModeler::SetSwappingData().
NodeIterator Kratos::ModelPart::NodesBegin (IndexType ThisIndex = 0) inline
Referenced by Kratos::ParallelDistanceCalculator< TDim >::AbsDistancesOnDividedElements(), Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), Kratos::VariableUtils::AddDof(), Kratos::VariableUtils::AddDofWithReaction(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurfaceAndHigher(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurfaceAndLower(), Kratos::CuttingUtility::AddSkinConditions(), Kratos::ParallelDistanceCalculator< TDim >::AssignDistanceSign(), Kratos::CuttingUtility::Calculate_Coordinate_And_Insert_New_Nodes_Mod(), Kratos::BodyNormalCalculationUtils::CalculateBodyNormals(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances2D(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances3D(), Kratos::ParallelDistanceCalculator< TDim >::CalculateDistancesLagrangianSurface(), Kratos::ParallelDistanceCalculator< TDim >::CalculateExactDistancesOnDividedElements(), Kratos::CalculateDistanceToSkinProcess::CalculateNodesDistances(), Kratos::CartesianMeshGeneratorModeler::CalculateNormals(), Kratos::NormalCalculationUtils::CalculateOnSimplex(), Kratos::NormalCalculationUtils::CalculateOnSimplexLowMemory(), Kratos::ParallelDistanceCalculator< TDim >::Check(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::Check(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::ClearGradient(), CloneSolutionStep(), Kratos::MeshNodeCollapsingProcess::CollapseNodes(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::IsosurfacePrinterApplication::CreateNodesArray(), Kratos::ReorderAndOptimizeModelPartProcess::Execute(), Kratos::FindNodalHProcess::Execute(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::CalculateNodalAreaProcess::Execute(), Kratos::ParallelDistanceCalculator< TDim >::ExtendDistancesByLayer(), Kratos::MeshSuiteModeler::FixNodes(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::FindIntersectedGeometricalObjectsProcess::GenerateOctree(), Kratos::CalculateDiscontinuousDistanceToSkinProcess::Initialize(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::LevelSetConvectionProcess< TDim >::LevelSetConvectionProcess(), Kratos::LineSearchesUtils< TSparseSpace, TDenseSpace, TLinearSolver >::MoveMesh(), Kratos::ParticleConvectUtily< TDim >::MoveParticles_RK4(), Kratos::ParticleConvectUtily< TDim >::MoveParticles_Substepping(), Kratos::ReorderAndOptimizeModelPartProcess::OptimizeOrdering(), OverwriteSolutionStepData(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::PeakValuesCorrection(), Kratos::MeshLocalSmoothingProcess::PerformSmoothing(), Kratos::MeshSmoothingProcess::PerformSmoothing(), Kratos::ComputeNodalGradientProcess< TDim, TVarType, THist >::PonderateGradient(), Kratos::CoordinateTransformationUtils< LocalSystemMatrixType, LocalSystemVectorType, double >::RecoverVelocities(), Kratos::AdaptiveResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::ReductionStrategy(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::MeshSuiteModeler::ReGenerateMesh(), Kratos::ConnectivityPreserveModeler::ResetModelPart(), Kratos::ParallelDistanceCalculator< TDim >::ResetVariables(), Kratos::CoordinateTransformationUtils< LocalSystemMatrixType, LocalSystemVectorType, double >::RotateVelocities(), Kratos::MeshCoarseningProcess::SelectCoarseMeshNodes(), Kratos::MeshLocalSmoothingProcess::SelectLowQualityElementNodes(), SetBufferSize(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::SetMaximumAndMinimumDistanceValues(), Kratos::MeshSuiteModeler::SetMesh(), SetNodalSolutionStepVariablesList(), Kratos::FindIntersectedGeometricalObjectsProcess::SetOctreeBoundingBox(), Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::SetUpDofSet(), Kratos::VariableUtils::SumHistoricalNodeScalarVariable(), Kratos::VariableUtils::SumHistoricalNodeVectorVariable(), Kratos::VariableUtils::SumNonHistoricalNodeScalarVariable(), Kratos::VariableUtils::SumNonHistoricalNodeVectorVariable(), Kratos::CuttingUtility::UpdateCutData(), Kratos::MeshSuiteModeler::UpdateMesh(), Kratos::BinBasedNodesInElementLocator< TDim >::UpdateSearchDatabase(), Kratos::BinBasedNodesInElementLocator< TDim >::UpdateSearchDatabaseAssignedSize(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::VariationalDistanceCalculationProcess(), Kratos::EdgeSwapping2DModeler::WriteMesh(), and ~ModelPart().
NodeConstantIterator Kratos::ModelPart::NodesBegin (IndexType ThisIndex = 0) const inline
NodeIterator Kratos::ModelPart::NodesEnd (IndexType ThisIndex = 0) inline
Referenced by AddNodes(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurfaceAndHigher(), Kratos::IsosurfacePrinterApplication::AddScalarVarIsosurfaceAndLower(), Kratos::BodyNormalCalculationUtils::CalculateBodyNormals(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances2D(), Kratos::SignedDistanceCalculationUtils< TDim >::CalculateDistances3D(), Kratos::CartesianMeshGeneratorModeler::CalculateNormals(), Kratos::NormalCalculationUtils::CalculateOnSimplex(), Kratos::NormalCalculationUtils::CalculateOnSimplexLowMemory(), Kratos::SolvingStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::Check(), Kratos::ResidualBasedBossakDisplacementScheme< TSparseSpace, TDenseSpace >::Check(), Kratos::KratosJsonIO::CheckAndAssignNodalComponentValue(), Kratos::KratosJsonIO::CheckAndAssignNodalValue(), Kratos::KratosJsonIO::CheckAndAssignNodalValue_ErrorIfFixed(), Kratos::MeshNodeCollapsingProcess::CollapseNodes(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), CreateNewNode(), Kratos::IsosurfacePrinterApplication::CreateNodesArray(), Kratos::FastTransferBetweenModelPartsProcess::Execute(), Kratos::CalculateNodalAreaProcess::Execute(), Kratos::MeshSuiteModeler::FixNodes(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::FindIntersectedGeometricalObjectsProcess::GenerateOctree(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::LineSearchesUtils< TSparseSpace, TDenseSpace, TLinearSolver >::MoveMesh(), OverwriteSolutionStepData(), Kratos::MeshLocalSmoothingProcess::PerformSmoothing(), Kratos::MeshSmoothingProcess::PerformSmoothing(), Kratos::AdaptiveResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::ReductionStrategy(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), Kratos::MeshSuiteModeler::ReGenerateMesh(), Kratos::ConnectivityPreserveModeler::ResetModelPart(), Kratos::MeshCoarseningProcess::SelectCoarseMeshNodes(), Kratos::MeshLocalSmoothingProcess::SelectLowQualityElementNodes(), Kratos::MeshSuiteModeler::SetMesh(), SetNodalSolutionStepVariablesList(), Kratos::FindIntersectedGeometricalObjectsProcess::SetOctreeBoundingBox(), Kratos::ResidualBasedEliminationBuilderAndSolverComponentwise< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::SetUpDofSet(), Kratos::ResidualBasedEliminationBuilderAndSolverSlip< TSparseSpace, TDenseSpace, TLinearSolver, TVariableType >::SetUpDofSet(), Kratos::CuttingUtility::UpdateCutData(), Kratos::MeshSuiteModeler::UpdateMesh(), Kratos::BinBasedNodesInElementLocator< TDim >::UpdateSearchDatabase(), Kratos::BinBasedNodesInElementLocator< TDim >::UpdateSearchDatabaseAssignedSize(), Kratos::EdgeSwapping2DModeler::WriteMesh(), and ~ModelPart().
NodeConstantIterator Kratos::ModelPart::NodesEnd (IndexType ThisIndex = 0) const inline
SizeType Kratos::ModelPart::NumberOfConditions (IndexType ThisIndex = 0) const inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::ConnectivityPreserveModeler::DuplicateConditions(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::Python::ModelPartNumberOfConditions1(), Kratos::VariableUtils::SumConditionScalarVariable(), and Kratos::VariableUtils::SumConditionVectorVariable().
SizeType Kratos::ModelPart::NumberOfElements (IndexType ThisIndex = 0) const inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::CartesianMeshGeneratorModeler::CalculateBoundingBox(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::CalculateEmbeddedVelocity(), Kratos::EdgeSwapping2DModeler::CollapseNodes(), Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::ConnectivityPreserveModeler::DuplicateElements(), Kratos::FindIntersectedGeometricalObjectsProcess::Execute(), Kratos::FindIntersectedGeometricalObjectsProcess::FindIntersectedSkinObjects(), Kratos::EdgeSwapping2DModeler::FindNodalNeighbours(), Kratos::CalculateDiscontinuousDistanceToSkinProcess::Initialize(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::EdgeSwapping2DModeler::MarkBadQualityElements(), Kratos::Python::ModelPartNumberOfElements1(), Kratos::EdgeSwapping2DModeler::Remesh(), Kratos::MeshLocalSmoothingProcess::SelectLowQualityElementNodes(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::SetMaximumAndMinimumDistanceValues(), Kratos::EdgeSwapping2DModeler::SetSwappingData(), Kratos::VariableUtils::SumElementScalarVariable(), and Kratos::VariableUtils::SumElementVectorVariable().
SizeType Kratos::ModelPart::NumberOfMeshes () inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ApplyConstantVectorValueProcess::ApplyConstantVectorValueProcess(), Kratos::Python::ModelPartGetMesh2(), and Kratos::ModelPartIO::ReadMeshBlock().
SizeType Kratos::ModelPart::NumberOfNodes (IndexType ThisIndex = 0) const inline
Referenced by Kratos::VariableUtils::AddDof(), Kratos::VariableUtils::AddDofWithReaction(), Kratos::Python::AddModelPartToPython(), Kratos::CalculateDistanceToSkinProcess::CalculateNodesDistances(), Kratos::CartesianMeshGeneratorModeler::CalculateNormals(), Kratos::EdgeSwapping2DModeler::CollapseNodes(), Kratos::EdgeSwapping2DModeler::FindNodalNeighbours(), Kratos::CartesianMeshGeneratorModeler::GenerateMesh(), Kratos::CalculateDiscontinuousDistanceToSkinProcess::Initialize(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), Kratos::Python::ModelPartNumberOfNodes1(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::PeakValuesCorrection(), Kratos::EdgeSwapping2DModeler::Remesh(), Kratos::EdgeSwapping2DModeler::SetCollapsingData(), Kratos::CalculateEmbeddedSignedDistanceTo3DSkinProcess::SetMaximumAndMinimumDistanceValues(), Kratos::VariableUtils::SumHistoricalNodeScalarVariable(), Kratos::VariableUtils::SumHistoricalNodeVectorVariable(), Kratos::VariableUtils::SumNonHistoricalNodeScalarVariable(), and Kratos::VariableUtils::SumNonHistoricalNodeVectorVariable().
SizeType Kratos::ModelPart::NumberOfProperties (IndexType ThisIndex = 0) const inline
Referenced by Kratos::Python::AddModelPartToPython(), and Kratos::Python::ModelPartNumberOfProperties1().
SizeType Kratos::ModelPart::NumberOfSubModelParts () const inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), and PrintData().
SizeType Kratos::ModelPart::NumberOfTables () const inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::TranslationOperation::ExecuteInitializeSolutionStep(), Kratos::RotationOperation::ExecuteInitializeSolutionStep(), and PrintData().
ModelPart & Kratos::ModelPart::operator= (ModelPart const & rOther)
Assignment operator.
References mBufferSize, mIndices, mMeshes, mName, mpProcessInfo, mpVariablesList, and mSubModelParts.
void Kratos::ModelPart::OverwriteSolutionStepData (IndexType SourceSolutionStepIndex, IndexType DestinationSourceSolutionStepIndex)
References IsSubModelPart(), KRATOS_THROW_ERROR, Name(), NodesBegin(), and NodesEnd().
Referenced by Kratos::Python::AddModelPartToPython(), and ReduceTimeStep().
ConditionsContainerType::Pointer Kratos::ModelPart::pConditions (IndexType ThisIndex = 0) inline
Referenced by Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::Python::ModelPartGetConditions1(), and Kratos::Python::ModelPartGetConditions2().
ElementsContainerType::Pointer Kratos::ModelPart::pElements (IndexType ThisIndex = 0) inline
Referenced by Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData(), Kratos::Python::ModelPartGetElements1(), and Kratos::Python::ModelPartGetElements2().
Communicator::Pointer Kratos::ModelPart::pGetCommunicator () inline
ConditionType::Pointer Kratos::ModelPart::pGetCondition (IndexType ConditionId, IndexType ThisIndex = 0) inline
Returns the Condition::Pointer corresponding to it's identifier
Referenced by Kratos::KratosJsonIO::FillModelPart(), Kratos::Python::ModelPartGetCondition1(), and Kratos::Python::ModelPartGetCondition2().
ElementType::Pointer Kratos::ModelPart::pGetElement (IndexType ElementId, IndexType ThisIndex = 0) inline
Returns the Element::Pointer corresponding to it's identifier
Referenced by Kratos::KratosJsonIO::FillModelPart(), Kratos::Python::ModelPartGetElement1(), and Kratos::Python::ModelPartGetElement2().
MeshType::Pointer Kratos::ModelPart::pGetMesh (IndexType ThisIndex = 0) inline
Referenced by ModelPart(), Kratos::Python::ModelPartGetMesh(), and Kratos::Python::ModelPartGetMesh2().
const MeshType::Pointer Kratos::ModelPart::pGetMesh (IndexType ThisIndex = 0) const inline
NodeType::Pointer Kratos::ModelPart::pGetNode (IndexType NodeId, IndexType ThisIndex = 0) inline
Returns the Node::Pointer corresponding to it's identifier
Referenced by AddConditions(), AddElements(), Kratos::KratosJsonIO::FillModelPart(), Kratos::DuplicateMeshModeler::GenerateMesh(), Kratos::Python::ModelPartCreateNewCondition(), Kratos::Python::ModelPartCreateNewElement(), Kratos::Python::ModelPartGetNode1(), Kratos::Python::ModelPartGetNode2(), Kratos::GeometryTesterUtility::TestHexahedra3D20N(), Kratos::GeometryTesterUtility::TestHexahedra3D27N(), Kratos::GeometryTesterUtility::TestHexahedra3D8N(), Kratos::GeometryTesterUtility::TestPrism3D6N(), Kratos::GeometryTesterUtility::TestQuadrilateral2D4N(), Kratos::GeometryTesterUtility::TestQuadrilateral2D9N(), Kratos::GeometryTesterUtility::TestTetrahedra3D10N(), Kratos::GeometryTesterUtility::TestTetrahedra3D4N(), Kratos::GeometryTesterUtility::TestTriangle2D3N(), and Kratos::GeometryTesterUtility::TestTriangle2D6N().
ProcessInfo::Pointer Kratos::ModelPart::pGetProcessInfo () inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), and Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart().
const ProcessInfo::Pointer Kratos::ModelPart::pGetProcessInfo () const inline
PropertiesType::Pointer Kratos::ModelPart::pGetProperties (IndexType PropertiesId, IndexType ThisIndex = 0) inline
Returns the Properties::Pointer corresponding to it's identifier
Referenced by Kratos::KratosJsonIO::FillModelPart(), Kratos::StructuredMeshGeneratorProcess::GenerateTetrahedraElements(), Kratos::StructuredMeshGeneratorProcess::GenerateTriangularElements(), and Kratos::Python::ModelPartGetPropertiesById().
TableType::Pointer Kratos::ModelPart::pGetTable (IndexType TableId) inline
Returns the Table::Pointer corresponding to it's identifier
Referenced by Kratos::Python::AddModelPartToPython().
NodesContainerType::Pointer Kratos::ModelPart::pNodes (IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::ModelPartGetNodes1(), and Kratos::Python::ModelPartGetNodes2().
PropertiesContainerType::Pointer Kratos::ModelPart::pProperties (IndexType ThisIndex = 0) inline
Referenced by AddElements(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::Python::ModelPartGetProperties1(), Kratos::Python::ModelPartGetProperties2(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), and Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart().
void Kratos::ModelPart::PrintData (std::ostream & rOStream) const override virtual
Print object's data.
Reimplemented from Kratos::DataValueContainer.
References GetMesh(), IsSubModelPart(), mBufferSize, mMeshes, mpProcessInfo, NumberOfSubModelParts(), NumberOfTables(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::PrintData(), Kratos::PointerVector< TDataType, TPointerType, TContainerType >::size(), SubModelPartsBegin(), and SubModelPartsEnd().
void Kratos::ModelPart::PrintData (std::ostream & rOStream, std::string const & PrefixString) const virtual
Print object's data.
References GetMesh(), IsSubModelPart(), mBufferSize, mMeshes, mpProcessInfo, NumberOfSubModelParts(), NumberOfTables(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::PrintData(), Kratos::PointerVector< TDataType, TPointerType, TContainerType >::size(), SubModelPartsBegin(), and SubModelPartsEnd().
void Kratos::ModelPart::PrintInfo (std::ostream & rOStream) const override virtual
Print information about this object.
Reimplemented from Kratos::DataValueContainer.
References Info().
Referenced by operation.Operation::ExecuteAfterOutputStep(), operation.Operation::ExecuteBeforeOutputStep(), operation.Operation::ExecuteBeforeSolutionLoop(), operation.Operation::ExecuteFinalize(), operation.Operation::ExecuteFinalizeSolutionStep(), operation.Operation::ExecuteInitialize(), and operation.Operation::ExecuteInitializeSolutionStep().
void Kratos::ModelPart::PrintInfo (std::ostream & rOStream, std::string const & PrefixString) const virtual
Print information about this object.
References Info().
Referenced by operation.Operation::ExecuteAfterOutputStep(), operation.Operation::ExecuteBeforeOutputStep(), operation.Operation::ExecuteBeforeSolutionLoop(), operation.Operation::ExecuteFinalize(), operation.Operation::ExecuteFinalizeSolutionStep(), operation.Operation::ExecuteInitialize(), and operation.Operation::ExecuteInitializeSolutionStep().
PropertiesContainerType::ContainerType& Kratos::ModelPart::PropertiesArray (IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::AddModelPartToPython(), and Kratos::DuplicateMeshModeler::GenerateMesh().
PropertiesIterator Kratos::ModelPart::PropertiesBegin (IndexType ThisIndex = 0) inline
PropertiesConstantIterator Kratos::ModelPart::PropertiesBegin (IndexType ThisIndex = 0) const inline
PropertiesIterator Kratos::ModelPart::PropertiesEnd (IndexType ThisIndex = 0) inline
PropertiesConstantIterator Kratos::ModelPart::PropertiesEnd (IndexType ThisIndex = 0) const inline
void Kratos::ModelPart::ReduceTimeStep (ModelPart & rModelPart, double NewTime)
ATTENTION: this function does not touch the coordinates of the nodes. It just resets the database values to the values at the beginning of the time step
References GetProcessInfo(), IsSubModelPart(), KRATOS_CATCH, KRATOS_THROW_ERROR, KRATOS_TRY, Name(), OverwriteSolutionStepData(), and Kratos::ProcessInfo::SetCurrentTime().
Referenced by Kratos::Python::AddModelPartToPython(), and Kratos::AdaptiveResidualBasedNewtonRaphsonStrategy< TSparseSpace, TDenseSpace, TLinearSolver >::ReductionStrategy().
void Kratos::ModelPart::RemoveCondition (ModelPart::IndexType ConditionId, ModelPart::IndexType ThisIndex = 0)
Remove the condition with given Id from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveCondition(), SubModelPartsBegin(), and SubModelPartsEnd().
Referenced by Kratos::Python::ModelPartRemoveCondition1(), Kratos::Python::ModelPartRemoveCondition2(), Kratos::Python::ModelPartRemoveCondition3(), Kratos::Python::ModelPartRemoveCondition4(), RemoveCondition(), and RemoveConditionFromAllLevels().
void Kratos::ModelPart::RemoveCondition (ModelPart::ConditionType & ThisCondition, ModelPart::IndexType ThisIndex = 0)
Remove given condition from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveCondition(), RemoveCondition(), SubModelPartsBegin(), and SubModelPartsEnd().
void Kratos::ModelPart::RemoveCondition (ConditionType::Pointer pThisCondition, IndexType ThisIndex = 0)
Remove given condition from mesh with ThisIndex in this modelpart and all its subs.
void Kratos::ModelPart::RemoveConditionFromAllLevels (ModelPart::IndexType ConditionId, ModelPart::IndexType ThisIndex = 0)
Remove the condition with given Id from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, and RemoveCondition().
Referenced by Kratos::Python::ModelPartRemoveConditionFromAllLevels1(), Kratos::Python::ModelPartRemoveConditionFromAllLevels2(), Kratos::Python::ModelPartRemoveConditionFromAllLevels3(), Kratos::Python::ModelPartRemoveConditionFromAllLevels4(), and RemoveConditionFromAllLevels().
void Kratos::ModelPart::RemoveConditionFromAllLevels (ModelPart::ConditionType & ThisCondition, ModelPart::IndexType ThisIndex = 0)
Remove given condition from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, RemoveCondition(), and RemoveConditionFromAllLevels().
void Kratos::ModelPart::RemoveConditionFromAllLevels (ConditionType::Pointer pThisCondition, IndexType ThisIndex = 0)
Remove given condition from mesh with ThisIndex in parents, itself and children.
void Kratos::ModelPart::RemoveConditions (Flags identifier_flag = TO_ERASE)
erases all elements identified by "identifier_flag" by removing the pointer. Pointers are erased from this level downwards nodes will be automatically destructured when no pointer is left to them
References Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), GetMeshes(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::reserve(), SubModelPartsBegin(), SubModelPartsEnd(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::swap().
Referenced by Kratos::ConditionEraseProcess::Execute(), RemoveConditionsFromAllLevels(), and Kratos::ConnectivityPreserveModeler::ResetModelPart().
void Kratos::ModelPart::RemoveConditionsFromAllLevels (Flags identifier_flag = TO_ERASE)
erases all elements identified by "identifier_flag" by removing the pointer. Pointers will be erase from all levels nodes will be automatically destructured when no pointer is left to them
References GetRootModelPart(), and RemoveConditions().
void Kratos::ModelPart::RemoveElement (ModelPart::IndexType ElementId, ModelPart::IndexType ThisIndex = 0)
Remove the element with given Id from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveElement(), SubModelPartsBegin(), and SubModelPartsEnd().
Referenced by Kratos::Python::ModelPartRemoveElement1(), Kratos::Python::ModelPartRemoveElement2(), Kratos::Python::ModelPartRemoveElement3(), Kratos::Python::ModelPartRemoveElement4(), RemoveElement(), and RemoveElementFromAllLevels().
void Kratos::ModelPart::RemoveElement (ModelPart::ElementType & ThisElement, ModelPart::IndexType ThisIndex = 0)
Remove given element from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveElement(), RemoveElement(), SubModelPartsBegin(), and SubModelPartsEnd().
void Kratos::ModelPart::RemoveElement (ElementType::Pointer pThisElement, IndexType ThisIndex = 0)
Remove given element from mesh with ThisIndex in this modelpart and all its subs.
void Kratos::ModelPart::RemoveElementFromAllLevels (ModelPart::IndexType ElementId, ModelPart::IndexType ThisIndex = 0)
Remove the element with given Id from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, and RemoveElement().
Referenced by Kratos::Python::ModelPartRemoveElementFromAllLevels1(), Kratos::Python::ModelPartRemoveElementFromAllLevels2(), Kratos::Python::ModelPartRemoveElementFromAllLevels3(), Kratos::Python::ModelPartRemoveElementFromAllLevels4(), and RemoveElementFromAllLevels().
void Kratos::ModelPart::RemoveElementFromAllLevels (ModelPart::ElementType & ThisElement, ModelPart::IndexType ThisIndex = 0)
Remove given element from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, RemoveElement(), and RemoveElementFromAllLevels().
void Kratos::ModelPart::RemoveElementFromAllLevels (ElementType::Pointer pThisElement, IndexType ThisIndex = 0)
Remove given element from mesh with ThisIndex in parents, itself and children.
void Kratos::ModelPart::RemoveElements (Flags identifier_flag = TO_ERASE)
erases all elements identified by "identifier_flag" by removing the pointer. Pointers are erased from this level downwards nodes will be automatically destructured when no pointer is left to them
References Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), GetMeshes(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::reserve(), SubModelPartsBegin(), SubModelPartsEnd(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::swap().
Referenced by Kratos::MeshNodeCollapsingProcess::Execute(), Kratos::ElementEraseProcess::Execute(), RemoveElementsFromAllLevels(), and Kratos::ConnectivityPreserveModeler::ResetModelPart().
void Kratos::ModelPart::RemoveElementsFromAllLevels (Flags identifier_flag = TO_ERASE)
erases all elements identified by "identifier_flag" by removing the pointer. Pointers will be erase from all levels nodes will be automatically destructured when no pointer is left to them
References GetRootModelPart(), and RemoveElements().
Referenced by Kratos::Python::ModelPartRemoveElementsFromAllLevels().
void Kratos::ModelPart::RemoveNode (ModelPart::IndexType NodeId, ModelPart::IndexType ThisIndex = 0)
Remove the node with given Id from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveNode(), SubModelPartsBegin(), and SubModelPartsEnd().
Referenced by Kratos::Python::ModelPartRemoveNode1(), Kratos::Python::ModelPartRemoveNode2(), Kratos::Python::ModelPartRemoveNode3(), Kratos::Python::ModelPartRemoveNode4(), RemoveNode(), and RemoveNodeFromAllLevels().
void Kratos::ModelPart::RemoveNode (ModelPart::NodeType & ThisNode, ModelPart::IndexType ThisIndex = 0)
Remove given node from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveNode(), RemoveNode(), SubModelPartsBegin(), and SubModelPartsEnd().
void Kratos::ModelPart::RemoveNode (NodeType::Pointer pThisNode, IndexType ThisIndex = 0)
Remove given node from mesh with ThisIndex in this modelpart and all its subs.
void Kratos::ModelPart::RemoveNodeFromAllLevels (ModelPart::IndexType NodeId, ModelPart::IndexType ThisIndex = 0)
Remove the node with given Id from mesh with ThisIndex in parents and children.
Remove the node with given Id from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, RemoveNode(), and RemoveNodeFromAllLevels().
Referenced by Kratos::Python::ModelPartRemoveNodeFromAllLevels1(), Kratos::Python::ModelPartRemoveNodeFromAllLevels2(), Kratos::Python::ModelPartRemoveNodeFromAllLevels3(), Kratos::Python::ModelPartRemoveNodeFromAllLevels4(), and RemoveNodeFromAllLevels().
void Kratos::ModelPart::RemoveNodeFromAllLevels (ModelPart::NodeType & ThisNode, ModelPart::IndexType ThisIndex = 0)
Remove given node from current mesh with ThisIndex in parents and children.
Remove given node from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, RemoveNode(), and RemoveNodeFromAllLevels().
void Kratos::ModelPart::RemoveNodeFromAllLevels (NodeType::Pointer pThisNode, IndexType ThisIndex = 0)
Remove given node from current mesh with ThisIndex in parents and children.
void Kratos::ModelPart::RemoveNodes (Flags identifier_flag = TO_ERASE)
erases all nodes identified by "identifier_flag" by removing the pointer. Pointers are erased from this level downwards nodes will be automatically destructured when no pointer is left to them
References Kratos::PointerVector< TDataType, TPointerType, TContainerType >::begin(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::begin(), Kratos::PointerVector< TDataType, TPointerType, TContainerType >::end(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::end(), GetMeshes(), Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::reserve(), SubModelPartsBegin(), SubModelPartsEnd(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::swap().
Referenced by Kratos::MeshNodeCollapsingProcess::Execute(), Kratos::NodeEraseProcess::Execute(), RemoveNodesFromAllLevels(), and Kratos::ConnectivityPreserveModeler::ResetModelPart().
void Kratos::ModelPart::RemoveNodesFromAllLevels (Flags identifier_flag = TO_ERASE)
erases all nodes identified by "identifier_flag" by removing the pointer. Pointers will be erase from all levels nodes will be automatically destructured when no pointer is left to them
References GetRootModelPart(), and RemoveNodes().
Referenced by Kratos::Python::ModelPartRemoveNodesFromAllLevels().
void Kratos::ModelPart::RemoveProperties (ModelPart::IndexType PropertiesId, IndexType ThisIndex = 0)
Remove the Properties with given Id from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveProperties(), SubModelPartsBegin(), and SubModelPartsEnd().
Referenced by Kratos::Python::ModelPartRemoveProperties1(), Kratos::Python::ModelPartRemoveProperties2(), Kratos::Python::ModelPartRemoveProperties3(), Kratos::Python::ModelPartRemoveProperties4(), RemoveProperties(), and RemovePropertiesFromAllLevels().
void Kratos::ModelPart::RemoveProperties (ModelPart::PropertiesType & ThisProperties, ModelPart::IndexType ThisIndex = 0)
Remove given Properties from mesh with ThisIndex in this modelpart and all its subs.
References GetMesh(), Kratos::Mesh< TNodeType, TPropertiesType, TElementType, TConditionType >::RemoveProperties(), RemoveProperties(), SubModelPartsBegin(), and SubModelPartsEnd().
void Kratos::ModelPart::RemoveProperties (PropertiesType::Pointer pThisProperties, IndexType ThisIndex = 0)
Remove given Properties from mesh with ThisIndex in this modelpart and all its subs.
void Kratos::ModelPart::RemovePropertiesFromAllLevels (ModelPart::IndexType PropertiesId, IndexType ThisIndex = 0)
Remove the Properties with given Id from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, RemoveProperties(), and RemovePropertiesFromAllLevels().
Referenced by Kratos::Python::ModelPartRemovePropertiesFromAllLevels1(), Kratos::Python::ModelPartRemovePropertiesFromAllLevels2(), Kratos::Python::ModelPartRemovePropertiesFromAllLevels3(), Kratos::Python::ModelPartRemovePropertiesFromAllLevels4(), and RemovePropertiesFromAllLevels().
void Kratos::ModelPart::RemovePropertiesFromAllLevels (ModelPart::PropertiesType & ThisProperties, ModelPart::IndexType ThisIndex = 0)
Remove given Properties from mesh with ThisIndex in parents, itself and children.
References IsSubModelPart(), mpParentModelPart, RemoveProperties(), and RemovePropertiesFromAllLevels().
void Kratos::ModelPart::RemovePropertiesFromAllLevels (PropertiesType::Pointer pThisProperties, IndexType ThisIndex = 0)
Remove given Properties from mesh with ThisIndex in parents, itself and children.
void Kratos::ModelPart::RemoveSubModelPart (std::string const & ThisSubModelPartName)
Remove a sub modelpart with given name.
References Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::iterator_adaptor::base(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::end(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::erase(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::find(), and mSubModelParts.
Referenced by Kratos::Python::RemoveSubModelPart1(), and Kratos::Python::RemoveSubModelPart2().
void Kratos::ModelPart::RemoveSubModelPart (ModelPart & ThisSubModelPart)
Remove given sub model part.
References Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::iterator_adaptor::base(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::end(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::erase(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::find(), KRATOS_THROW_ERROR, mSubModelParts, and Name().
void Kratos::ModelPart::RemoveTable (ModelPart::IndexType TableId)
Remove the Table with given Id from current mesh in this modelpart and all its subs.
Remove the Table with given Id from current mesh.
References Kratos::PointerVectorMap< TKeyType, TDataType, TCompareType, TPointerType, TContainerType >::erase(), mTables, SubModelPartsBegin(), and SubModelPartsEnd().
Referenced by RemoveTableFromAllLevels().
void Kratos::ModelPart::RemoveTableFromAllLevels (ModelPart::IndexType TableId)
Remove the Table with given Id from current mesh in parents, itself and all children.
References IsSubModelPart(), mpParentModelPart, RemoveTable(), and RemoveTableFromAllLevels().
Referenced by RemoveTableFromAllLevels().
PropertiesContainerType& Kratos::ModelPart::rProperties (IndexType ThisIndex = 0) inline
temporarily renamed Properties() function because the declaration of Properties() here violates the declaration of Properties() in properties.h (janosch, in agreement with pooyan)
Referenced by Kratos::CalculateSignedDistanceTo3DSkinProcess::GenerateSkinModelPart(), Kratos::ModelPartIO::ReadConditionsBlock(), Kratos::ModelPartIO::ReadElementsBlock(), Kratos::ModelPartIO::ReadModelPart(), and Kratos::ModelPartIO::ReadSubModelPartPropertiesBlock().
void Kratos::ModelPart::save (Serializer & rSerializer) const override private virtual
Reimplemented from Kratos::DataValueContainer.
References KRATOS_SERIALIZE_SAVE_BASE_CLASS, mBufferSize, mMeshes, mName, mpProcessInfo, mpVariablesList, mSubModelParts, and Kratos::Serializer::save().
void Kratos::ModelPart::SetBufferSize (ModelPart::IndexType NewBufferSize)
References Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::begin(), Kratos::PointerHashMapSet< TDataType, THashType, TGetKeyType, TPointerType >::end(), IsSubModelPart(), KRATOS_THROW_ERROR, mBufferSize, mSubModelParts, Name(), Nodes(), NodesBegin(), and Kratos::PointerVectorSet< TDataType, TGetKeyType, TCompareType, TEqualType, TPointerType, TContainerType >::size().
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), and Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE().
void Kratos::ModelPart::SetCommunicator (Communicator::Pointer pNewCommunicator) inline
Referenced by Kratos::ConnectivityPreserveModeler::DuplicateCommunicatorData().
void Kratos::ModelPart::SetConditions (ConditionsContainerType::Pointer pOtherConditions, IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::ModelPartSetConditions1(), and Kratos::Python::ModelPartSetConditions2().
void Kratos::ModelPart::SetElements (ElementsContainerType::Pointer pOtherElements, IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::ModelPartSetElements1(), and Kratos::Python::ModelPartSetElements2().
void Kratos::ModelPart::SetNodalSolutionStepVariablesList ()
References IsSubModelPart(), KRATOS_THROW_ERROR, mpVariablesList, Name(), NodesBegin(), and NodesEnd().
Referenced by Kratos::DatafileIO::ReadModelPart().
void Kratos::ModelPart::SetNodes (NodesContainerType::Pointer pOtherNodes, IndexType ThisIndex = 0) inline
Referenced by Kratos::Python::ModelPartSetNodes1(), and Kratos::Python::ModelPartSetNodes2().
void Kratos::ModelPart::SetParentModelPart (ModelPart * pParentModelPart) inline private
Referenced by AddSubModelPart(), and CreateSubModelPart().
void Kratos::ModelPart::SetProcessInfo (ProcessInfo::Pointer pNewProcessInfo) inline
Referenced by Kratos::Python::AddModelPartToPython(), Kratos::ConnectivityPreserveModeler::CopyCommonData(), and Kratos::Python::SetProcessInfo().
void Kratos::ModelPart::SetProcessInfo (ProcessInfo & NewProcessInfo) inline
void Kratos::ModelPart::SetProperties (PropertiesContainerType::Pointer pOtherProperties, IndexType ThisIndex = 0) inline
Referenced by Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::Python::ModelPartSetProperties1(), and Kratos::Python::ModelPartSetProperties2().
SubModelPartsContainerType& Kratos::ModelPart::SubModelParts () inline
Referenced by Kratos::ReorderAndOptimizeModelPartProcess::ActualizeSubModelPart(), and Kratos::ReorderAndOptimizeModelPartProcess::Execute().
SubModelPartIterator Kratos::ModelPart::SubModelPartsBegin () inline
Referenced by Kratos::ConnectivityPreserveModeler::DuplicateSubModelParts(), Kratos::ReplaceElementsAndConditionsProcess::Execute(), Kratos::Python::GetSubModelPartBegin(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), load(), PrintData(), RemoveCondition(), RemoveConditions(), RemoveElement(), RemoveElements(), RemoveNode(), RemoveNodes(), RemoveProperties(), RemoveTable(), Kratos::ReplaceElementsAndConditionsProcess::UpdateSubModelPart(), and ~ModelPart().
SubModelPartConstantIterator Kratos::ModelPart::SubModelPartsBegin () const inline
SubModelPartIterator Kratos::ModelPart::SubModelPartsEnd () inline
Referenced by Kratos::ConnectivityPreserveModeler::DuplicateSubModelParts(), Kratos::ReplaceElementsAndConditionsProcess::Execute(), Kratos::Python::GetSubModelPartEnd(), Kratos::Testing::KRATOS_TEST_CASE_IN_SUITE(), load(), PrintData(), RemoveCondition(), RemoveConditions(), RemoveElement(), RemoveElements(), RemoveNode(), RemoveNodes(), RemoveProperties(), RemoveTable(), Kratos::ReplaceElementsAndConditionsProcess::UpdateSubModelPart(), and ~ModelPart().
SubModelPartConstantIterator Kratos::ModelPart::SubModelPartsEnd () const inline
TablesContainerType& Kratos::ModelPart::Tables () inline
Referenced by Kratos::ConnectivityPreserveModeler::CopyCommonData(), Kratos::ModelPartIO::ReadModelPart(), Kratos::ModelPartIO::ReadSubModelPartTablesBlock(), Kratos::LevelSetConvectionProcess< TDim >::ReGenerateConvectionModelPart(), Kratos::VariationalDistanceCalculationProcess< TDim, TSparseSpace, TDenseSpace, TLinearSolver >::ReGenerateDistanceModelPart(), and Kratos::ModelPartIO::WriteModelPart().
TablesContainerType::ContainerType& Kratos::ModelPart::TablesArray () inline
TableIterator Kratos::ModelPart::TablesBegin () inline
TableConstantIterator Kratos::ModelPart::TablesBegin () const inline
TableIterator Kratos::ModelPart::TablesEnd () inline
TableConstantIterator Kratos::ModelPart::TablesEnd () const inline
Friends And Related Function Documentation
friend class Serializer friend
Member Data Documentation
IndexType Kratos::ModelPart::mBufferSize private
Referenced by AssignNode(), CloneSolutionStep(), CreateNewNode(), CreateSubModelPart(), load(), operator=(), PrintData(), save(), and SetBufferSize().
std::vector<IndexType> Kratos::ModelPart::mIndices private
Referenced by operator=().
MeshesContainerType Kratos::ModelPart::mMeshes private
Referenced by load(), ModelPart(), operator=(), PrintData(), save(), and ~ModelPart().
std::string Kratos::ModelPart::mName private
Referenced by Info(), load(), ModelPart(), operator=(), and save().
Communicator::Pointer Kratos::ModelPart::mpCommunicator private
Referenced by ModelPart(), and ~ModelPart().
ModelPart* Kratos::ModelPart::mpParentModelPart private
Referenced by AddCondition(), AddConditions(), AddElement(), AddElements(), AddNode(), AddProperties(), AddSubModelPart(), AddTable(), AssignNode(), CloneSolutionStep(), CreateNewNode(), GetRootModelPart(), RemoveConditionFromAllLevels(), RemoveElementFromAllLevels(), RemoveNodeFromAllLevels(), RemovePropertiesFromAllLevels(), and RemoveTableFromAllLevels().
ProcessInfo::Pointer Kratos::ModelPart::mpProcessInfo private
Referenced by CloneSolutionStep(), CloneTimeStep(), CreateSubModelPart(), CreateTimeStep(), load(), operator=(), PrintData(), and save().
VariablesList* Kratos::ModelPart::mpVariablesList private
Referenced by AssignNode(), CreateNewNode(), CreateSubModelPart(), load(), operator=(), save(), SetNodalSolutionStepVariablesList(), and ~ModelPart().
SubModelPartsContainerType Kratos::ModelPart::mSubModelParts private
Referenced by AddSubModelPart(), CreateSubModelPart(), GetSubModelPartNames(), load(), operator=(), RemoveSubModelPart(), save(), and SetBufferSize().
TablesContainerType Kratos::ModelPart::mTables private
Referenced by AddTable(), and RemoveTable().
The documentation for this class was generated from the following files:
/home/shahrokh/software/Kratos/kratos/includes/model_part.h
/home/shahrokh/software/Kratos/kratos/sources/model_part.cpp